-- Superseded by the applied Pass 4 migration:
-- supabase/migrations/20260910104008_pass4_gift_corrections.sql
-- Gift correction is now enabled. That migration limits movement-date edits
-- to gift-associated movements; no manual permission change is needed here.
