// @vitest-environment jsdom
import {afterEach,beforeEach,expect,it,vi} from 'vitest'
import {act,cleanup,fireEvent,render,screen,waitFor,within} from '@testing-library/react'
import {CellarShell} from './App'
import {EMPTY_CELLAR_DATA,type CellarData} from './lib/cellar-data'
import {installUnsavedNavigationGuard,pushCellarHistory} from './lib/unsaved-changes'
const api=vi.hoisted(()=>({load:vi.fn(),rpc:vi.fn(),sign:vi.fn(),invoke:vi.fn()}))
vi.mock('./lib/cellar-data',async original=>({...await original<typeof import('./lib/cellar-data')>(),loadCellarData:api.load}))
vi.mock('./lib/supabase',()=>({supabase:{rpc:api.rpc,functions:{invoke:api.invoke},storage:{from:()=>({createSignedUrl:api.sign})}},isSupabaseConfigured:true}))
const wine={id:'wine',name:'Test Red',wineryId:'winery',wineryName:'Test Winery',nonVintage:false,vintage:2023,availableQuantity:3,agingCount:0,storageNames:['Rack'],selectorNames:[],buyAgain:[],averageRating:null,createdAt:'2026-01-01'}
const data={...EMPTY_CELLAR_DATA,wines:[wine],wineries:[{id:'winery',name:'Test Winery',wineCount:1,visitCount:1}],visits:[{id:'visit',wineryId:'winery',visitDate:'2026-08-01',notes:'Our visit'}],purchases:[{id:'purchase',wineryVisitId:'visit',acquisitionDate:'2026-08-01'}],purchaseItems:[{id:'item',purchaseId:'purchase',wineId:'wine',quantity:3}],wineOnlineInfo:[{entityId:'wine',acceptedData:{category:'Red Wine'},confidence:'high'}]} as unknown as CellarData
beforeEach(()=>{vi.clearAllMocks();installUnsavedNavigationGuard();pushCellarHistory({cellarOverlay:null},'#/cellar');vi.spyOn(window,'confirm').mockReturnValue(false);HTMLElement.prototype.scrollTo=vi.fn();api.load.mockResolvedValue(data);api.rpc.mockResolvedValue({data:1,error:null});api.invoke.mockResolvedValue({data:{},error:null})})
afterEach(()=>{cleanup();vi.restoreAllMocks()})
async function mount(){render(<CellarShell household={{householdId:'household',role:'owner',displayName:'Tester'}} onSignOut={vi.fn()}/>);await waitFor(()=>expect((screen.getByRole('button',{name:'Refresh'}) as HTMLButtonElement).disabled).toBe(false))}
it('accepted Type appears in summary, search and filter and survives Back',async()=>{
 await mount();fireEvent.change(screen.getByLabelText('Search the cellar'),{target:{value:'Red Wine'}});expect(screen.getAllByRole('button',{name:'Open Test Red'}).length).toBeGreaterThan(0);fireEvent.click(screen.getByRole('button',{name:/Filters/}));fireEvent.change(screen.getByLabelText('Style / category'),{target:{value:'Red Wine'}});fireEvent.click(screen.getAllByRole('button',{name:'Open Test Red'})[0]);expect(screen.getByRole('dialog').textContent).toContain('Red Wine · accepted online info');fireEvent.click(screen.getByRole('button',{name:'Back'}));await waitFor(()=>expect(screen.queryByRole('dialog')).toBeNull());expect((screen.getByLabelText('Style / category') as HTMLSelectElement).value).toBe('Red Wine')
})
it('Aging stays usable without guidance, sends no invented hold year, and protects changes',async()=>{
 await mount();fireEvent.click(screen.getAllByRole('button',{name:'Open Test Red'})[0]);await act(async()=>{});fireEvent.click(screen.getByLabelText('Aging',{exact:true}));expect((screen.getByLabelText('Hold until') as HTMLInputElement).value).toBe('');fireEvent.click(screen.getByRole('button',{name:'Back'}));expect(window.confirm).toHaveBeenCalledOnce();fireEvent.click(screen.getByRole('button',{name:'Save Aging selection'}));await waitFor(()=>expect(api.rpc).toHaveBeenCalledWith('set_wine_aging_quantity',{p_household_id:'household',p_wine_id:'wine',p_aging_count:1,p_user_hold_override_year:null}))
})
it('Winery puts visits before wines and producer details, then opens associated wines',async()=>{
 await mount();fireEvent.click(screen.getByRole('button',{name:'Wineries'}));fireEvent.click(screen.getAllByRole('button',{name:'Open Test Winery'})[0]);const dialog=screen.getByRole('dialog');const headings=within(dialog).getAllByRole('heading',{level:3}).map(x=>x.textContent);expect(headings[0]).toBe('Our Visits');expect(headings[1]).toBe('Our Wines');expect(within(dialog).getByRole('button',{name:'Add Visit'})).toBeTruthy();fireEvent.click(within(dialog).getByRole('button',{name:/Our visit/}));expect(screen.getByRole('dialog').textContent).toContain('Test Red');expect(screen.getByRole('button',{name:'Add Wine Purchase'})).toBeTruthy()
})
it('History opening can be finished, rated, corrected and returned to without a second opening',async()=>{
 const opening={id:'opening',wineId:'wine',openedAt:'2026-08-01T12:00:00Z',status:'open',openedBy:'Scott'}
 api.load.mockResolvedValue({...data,people:[{id:'scott',displayName:'Scott'}],openings:[opening]});await mount();fireEvent.click(screen.getAllByRole('button',{name:'Open Test Red'})[0]);fireEvent.click(screen.getByRole('button',{name:'History'}));fireEvent.click(screen.getByRole('button',{name:/Bottle opened/}));fireEvent.click(screen.getByRole('button',{name:'Finish Bottle'}));await act(async()=>{});fireEvent.click(screen.getByRole('button',{name:'4 stars'}));fireEvent.change(screen.getByLabelText('Tasting notes'),{target:{value:'Reviewed later'}});api.load.mockResolvedValue({...data,people:[{id:'scott',displayName:'Scott'}],openings:[{...opening,status:'finished'}],reviews:[{id:'review',openingId:'opening',personId:'scott',rating:4,tastingNotes:'Reviewed later'}]});fireEvent.click(screen.getByRole('button',{name:'Save opening'}));await screen.findByRole('button',{name:'Edit tasting notes & rating'});expect(screen.getByRole('dialog').textContent).toContain('Reviewed later');expect(api.rpc).toHaveBeenCalledOnce();expect(api.rpc.mock.calls[0][0]).toBe('save_opening_review');expect(window.confirm).not.toHaveBeenCalled();fireEvent.click(screen.getByRole('button',{name:'Edit tasting notes & rating'}));expect((screen.getByLabelText('Tasting notes') as HTMLTextAreaElement).value).toBe('Reviewed later')
})
it('Pass 3 search/filter/sort and result counts survive detail Back; clear actions have separate scopes',async()=>{
 await mount();fireEvent.change(screen.getByLabelText('Search the cellar'),{target:{value:'Test'}});fireEvent.change(screen.getByLabelText('Sort wines'),{target:{value:'name'}});fireEvent.click(screen.getByRole('button',{name:/Filters/}));fireEvent.change(screen.getByLabelText('Style / category'),{target:{value:'Red Wine'}});fireEvent.click(screen.getAllByRole('button',{name:'Open Test Red'})[0]);const dialog=screen.getByRole('dialog');expect(dialog.textContent!.indexOf('Our experience')).toBeLessThan(dialog.textContent!.indexOf('When to Enjoy'));fireEvent.click(screen.getByRole('button',{name:'Back'}));await waitFor(()=>expect(screen.queryByRole('dialog')).toBeNull());expect((screen.getByLabelText('Sort wines') as HTMLSelectElement).value).toBe('name');fireEvent.click(screen.getByRole('button',{name:'Clear Search'}));expect((screen.getByLabelText('Search the cellar') as HTMLInputElement).value).toBe('');expect((screen.getByLabelText('Style / category') as HTMLSelectElement).value).toBe('Red Wine');fireEvent.change(screen.getByLabelText('Search the cellar'),{target:{value:'No such wine'}});fireEvent.click(screen.getByRole('button',{name:'Clear Filters'}));expect((screen.getByLabelText('Search the cellar') as HTMLInputElement).value).toBe('No such wine');fireEvent.click(screen.getAllByRole('button',{name:'Clear All'})[0]);expect(screen.getAllByRole('button',{name:'Open Test Red'}).length).toBeGreaterThan(0)
})
it.each(['Accept','Skip'])('Pass 3 queue opens directly at review and %s returns to the searched queue',async(action)=>{
 sessionStorage.clear();const attempt={id:'attempt',wineId:'wine',wineryId:null,status:'ready_for_review',confidence:'medium',proposedData:{category:'Red Wine'},createdAt:'2026-08-01',matchExplanation:'Review this vintage'};api.load.mockResolvedValue({...data,enrichmentAttempts:[attempt]});await mount();fireEvent.click(screen.getByRole('button',{name:'More'}));fireEvent.click(screen.getByRole('button',{name:/Data Enrichment/}));fireEvent.change(screen.getByLabelText('Search review queue'),{target:{value:'Test Winery'}});fireEvent.click(screen.getByRole('button',{name:/1 Ready for Review/}));fireEvent.click(screen.getByRole('button',{name:/Test Red.*Test Winery/}));expect(screen.getByText('Review suggested information')).toBeTruthy();expect(screen.queryByText('Our experience')).toBeNull();api.load.mockResolvedValue({...data,enrichmentAttempts:[{...attempt,status:action==='Accept'?'accepted':'rejected'}]});fireEvent.click(screen.getByRole('button',{name:new RegExp(`^${action}$`)}));await screen.findByLabelText('Search review queue');expect((screen.getByLabelText('Search review queue') as HTMLInputElement).value).toBe('Test Winery');expect(api.rpc).toHaveBeenCalledWith(action==='Accept'?'accept_enrichment_attempt':'reject_enrichment_attempt',expect.objectContaining({p_attempt_id:'attempt'}));expect(screen.getByText('0 matching records')).toBeTruthy()
})

it('Pass 3 renews long-session photo URLs and bounds automatic error recovery',async()=>{
 api.sign.mockImplementation(async()=>({data:{signedUrl:`https://photos.example/${api.sign.mock.calls.length}`},error:null}));api.load.mockResolvedValue({...data,photos:[{id:'photo',wineId:'wine',storagePath:'h/wine/photo.jpg'}]});await mount();await waitFor(()=>expect(api.sign).toHaveBeenCalledOnce());await act(async()=>{window.dispatchEvent(new CustomEvent('cellar-photo-error',{detail:'expired'}))});expect(api.sign).toHaveBeenCalledTimes(2);await act(async()=>{window.dispatchEvent(new CustomEvent('cellar-photo-error',{detail:'revoked-again'}))});expect(api.sign).toHaveBeenCalledTimes(2);vi.useFakeTimers();try {await act(async()=>{fireEvent.click(screen.getByRole('button',{name:'Retry Photos'}))});expect(api.sign).toHaveBeenCalledTimes(3);await act(async()=>{await vi.advanceTimersByTimeAsync(45*60*1000)});expect(api.sign).toHaveBeenCalledTimes(4)}finally{vi.useRealTimers()}
})
it('Pass 4 Save closes the busy entry form and Add Another retains context with blank wine fields',async()=>{
 api.load.mockResolvedValue({...data,locations:[{id:'rack',name:'Rack',isActive:true}],trips:[{id:'trip',name:'Trip',startDate:'2026-08-01',endDate:'2026-08-02'}]});api.rpc.mockResolvedValue({data:{purchase_id:'purchase',wine_ids:['wine'],winery_id:'winery',visit_id:'visit',trip_id:'trip'},error:null});await mount();fireEvent.click(screen.getByRole('button',{name:'Add something'}));fireEvent.click(screen.getByRole('button',{name:'Add Wine Add a wine and its bottles'}));fireEvent.change(screen.getByLabelText('Winery'),{target:{value:'Test Winery'}});fireEvent.click(screen.getByRole('button',{name:'Test Winery'}));fireEvent.change(screen.getByLabelText('Wine name'),{target:{value:'New wine'}});fireEvent.change(screen.getByLabelText('Purchase date'),{target:{value:'2026-08-01'}});fireEvent.click(screen.getByRole('button',{name:'Save'}));await screen.findByRole('button',{name:'Add Another'});expect(screen.queryByRole('dialog',{name:'Add Wine'})).toBeNull();expect(screen.getByRole('dialog').textContent).toContain('Test Red');expect(window.confirm).not.toHaveBeenCalled();fireEvent.click(screen.getByRole('button',{name:'Add Another'}));expect((screen.getByLabelText('Wine name') as HTMLInputElement).value).toBe('');expect((screen.getByLabelText('Winery') as HTMLInputElement).value).toBe('Test Winery');expect(screen.getByText(/Adding to the same purchase/)).toBeTruthy();expect((screen.getByLabelText('Quantity') as HTMLInputElement).value).toBe('1')
})
it.each(['Gift Bottle','Open Bottle'])('Pass 4 %s closes after saving the last bottle, restores updated Wine and never warns about saved edits',async(action)=>{
 const lots=[{wineId:'wine',purchaseId:'purchase',purchaseItemId:'item',storageLocationId:'rack',storageLocationName:'Rack',quantity:1,normalQuantity:1,agingQuantity:0}]
 api.load.mockResolvedValue({...data,wines:[{...wine,availableQuantity:1}],bottleLots:lots});await mount()
 fireEvent.click(screen.getAllByRole('button',{name:'Open Test Red'})[0]);fireEvent.click(screen.getByRole('button',{name:action}))
 const form=screen.getByRole('dialog',{name:action==='Gift Bottle'?'Gift Bottle':'Open / Gift Bottle'})
 expect(within(form).queryByLabelText('Bottle and location')).toBeNull()
 if(action==='Gift Bottle'){expect(within(form).getByLabelText('Opening date').matches(':disabled')).toBe(true);fireEvent.change(within(form).getByLabelText('Gifted to'),{target:{value:'Friend'}})}
 const gift={id:'gift',wineId:'wine',purchaseItemId:'item',storageLocationId:'rack',giftedTo:'Friend',giftedOn:'2026-09-10'}
 api.load.mockResolvedValue({...data,wines:[{...wine,availableQuantity:0}],bottleLots:[],giftsGiven:action==='Gift Bottle'?[gift]:[],openings:action==='Open Bottle'?[{id:'opening',wineId:'wine',openedAt:'2026-09-10T12:00:00Z',status:'open'}]:[]})
 fireEvent.click(within(form).getByRole('button',{name:'Save'}));await waitFor(()=>expect(screen.queryByRole('dialog',{name:action==='Gift Bottle'?'Gift Bottle':'Open / Gift Bottle'})).toBeNull())
 expect(api.rpc).toHaveBeenCalledOnce();expect(window.confirm).not.toHaveBeenCalled();expect(screen.queryByRole('button',{name:'Gift Bottle'})).toBeNull()
 fireEvent.click(screen.getByRole('button',{name:'History'}));expect(screen.getByRole('dialog').textContent).toContain(action==='Gift Bottle'?'Friend':'Bottle opened')
 fireEvent.click(screen.getByRole('button',{name:'Back'}));await waitFor(()=>expect(screen.queryByRole('dialog')).toBeNull());expect(window.confirm).not.toHaveBeenCalled()
})
it('Gift correction returns to the updated gift with no new inventory operation or unsaved warning',async()=>{
 const gift={id:'gift',wineId:'wine',purchaseItemId:'item',storageLocationId:'rack',giftedTo:'Friend',giftedOn:'2026-09-10',occasionNote:'Original'}
 api.load.mockResolvedValue({...data,giftsGiven:[gift]});await mount();fireEvent.click(screen.getAllByRole('button',{name:'Open Test Red'})[0]);fireEvent.click(screen.getByRole('button',{name:'History'}));fireEvent.click(screen.getByRole('button',{name:/Gift.*Friend/i}));fireEvent.click(screen.getByRole('button',{name:'Edit'}));fireEvent.change(screen.getByLabelText('Gifted to'),{target:{value:'Corrected Friend'}});api.load.mockResolvedValue({...data,giftsGiven:[{...gift,giftedTo:'Corrected Friend'}]});fireEvent.click(screen.getByRole('button',{name:'Save correction'}));await waitFor(()=>expect(screen.queryByRole('button',{name:'Save correction'})).toBeNull());expect(screen.getByRole('dialog').textContent).toContain('Corrected Friend');expect(api.rpc).toHaveBeenCalledOnce();expect(api.rpc.mock.calls[0][0]).toBe('correct_history_record');expect(window.confirm).not.toHaveBeenCalled()
})

it('manual Wine edit contains identity/personal fields only, saves atomically, and returns cleanly',async()=>{
 const current={...wine,category:'Manual Type',blendDescription:'Stored blend',officialWineryNotes:'Stored reference',personalNotes:'Our old note'}
 api.load.mockResolvedValue({...data,wines:[current],people:[{id:'scott',displayName:'Scott'}]});await mount();fireEvent.click(screen.getAllByRole('button',{name:'Open Test Red'})[0]);fireEvent.click(screen.getByRole('button',{name:'Edit'}));await act(async()=>{});
 for(const name of ['category','style','blend_description','official_winery_notes','country','state','closure','vineyard'])expect(document.querySelector(`input[name="${name}"],textarea[name="${name}"],select[name="${name}"]`)).toBeNull()
 fireEvent.change(screen.getByLabelText('Our notes'),{target:{value:'Our updated note'}});api.load.mockResolvedValue({...data,wines:[{...current,personalNotes:'Our updated note'}]});fireEvent.click(screen.getByRole('button',{name:'Save wine'}));await waitFor(()=>expect(screen.queryByRole('button',{name:'Save wine'})).toBeNull());expect(api.rpc).toHaveBeenCalledOnce();expect(api.rpc.mock.calls[0]).toEqual(['save_wine_personal',{p_household_id:'household',p_wine_id:'wine',p_fields:{winery_id:'winery',name:'Test Red',vintage:2023,non_vintage:false,personal_notes:'Our updated note',favorite:false},p_preferences:[{person_id:'scott',favorite:false,buy_again:null,notes:null}]}]);expect(screen.getByRole('dialog').textContent).toContain('Our updated note');fireEvent.click(screen.getByRole('button',{name:'Back'}));await waitFor(()=>expect(screen.queryByRole('dialog')).toBeNull());expect(window.confirm).not.toHaveBeenCalled()
})
it('changed Wine edit warns on Back; failed save preserves draft; refresh failure after success still finishes',async()=>{
 await mount();fireEvent.click(screen.getAllByRole('button',{name:'Open Test Red'})[0]);fireEvent.click(screen.getByRole('button',{name:'Edit'}));await act(async()=>{});fireEvent.change(screen.getByLabelText('Our notes'),{target:{value:'Keep this draft'}});fireEvent.click(screen.getByRole('button',{name:'Back'}));expect(window.confirm).toHaveBeenCalledOnce();api.rpc.mockResolvedValueOnce({error:{message:'Temporary failure'}});fireEvent.click(screen.getByRole('button',{name:'Save wine'}));await screen.findByText('The wine could not be saved. Please try again.');expect((screen.getByLabelText('Our notes') as HTMLTextAreaElement).value).toBe('Keep this draft');api.load.mockRejectedValueOnce(new Error('offline'));fireEvent.click(screen.getByRole('button',{name:'Save wine'}));await waitFor(()=>expect(screen.queryByRole('button',{name:'Save wine'})).toBeNull());expect(screen.getAllByRole('button',{name:'Retry Refresh'})[0]).toBeTruthy();fireEvent.click(screen.getByRole('button',{name:'Back'}));await waitFor(()=>expect(screen.queryByRole('dialog')).toBeNull());expect(window.confirm).toHaveBeenCalledOnce()
})
it('minimally entered Wine exposes Find Wine Info near inventory and accepts only sourced information',async()=>{
 const attempt={id:'attempt',wineId:'wine',status:'ready_for_review',confidence:'high',proposedData:{category:'Red Wine',description:'Producer reference'},createdAt:'2026-09-10'}
 api.load.mockResolvedValue({...data,wineOnlineInfo:[],enrichmentAttempts:[]});await mount();fireEvent.click(screen.getAllByRole('button',{name:'Open Test Red'})[0]);let content=screen.getByRole('dialog').textContent!;expect(content.indexOf('Online Wine Information')).toBeLessThan(content.indexOf('Our experience'));api.load.mockResolvedValue({...data,wineOnlineInfo:[],enrichmentAttempts:[attempt]});fireEvent.click(screen.getByRole('button',{name:'Find Wine Info'}));await screen.findByRole('button',{name:/^Accept$/});expect(api.invoke).toHaveBeenCalledOnce();api.load.mockResolvedValue({...data,wineOnlineInfo:[{entityId:'wine',acceptedData:attempt.proposedData,acceptedAttemptId:'attempt',confidence:'high'}],enrichmentAttempts:[{...attempt,status:'enriched'}]});fireEvent.click(screen.getByRole('button',{name:/^Accept$/}));await screen.findByText('Producer reference');expect(api.rpc).toHaveBeenCalledWith('accept_enrichment_attempt',expect.objectContaining({p_attempt_id:'attempt'}));expect(screen.getByRole('heading',{name:'Online Wine Information'})).toBeTruthy()
})
it.each([false,true])('Move returns to updated Wine, preserves context, and avoids dirty warnings (refresh fails: %s)',async(refreshFails)=>{
 const bottle={id:'bottle',wineId:'wine',purchaseItemId:'item',storageLocationId:'rack',status:'active',isAging:false}
 const initial={...data,wines:[{...wine,availableQuantity:1}],locations:[{id:'rack',name:'Rack',isActive:true},{id:'other',name:'Other Rack',isActive:true}],bottles:[bottle],bottleLots:[{wineId:'wine',storageLocationId:'rack',storageLocationName:'Rack',quantity:1,agingQuantity:0}]}
 api.load.mockResolvedValue(initial);await mount();fireEvent.change(screen.getByLabelText('Search the cellar'),{target:{value:'Test'}});fireEvent.click(screen.getAllByRole('button',{name:'Open Test Red'})[0]);fireEvent.click(screen.getByRole('button',{name:'Change Location'}));await act(async()=>{});expect(screen.queryByLabelText('Which bottles?')).toBeNull();expect(screen.queryByLabelText('How many bottles?')).toBeNull();fireEvent.change(screen.getByLabelText('Move to'),{target:{value:'other'}});
 const updated={...initial,wines:[{...wine,availableQuantity:1,storageNames:['Other Rack']}],bottles:[{...bottle,storageLocationId:'other'}],bottleLots:[{...initial.bottleLots[0],storageLocationId:'other',storageLocationName:'Other Rack'}]}
 if(refreshFails)api.load.mockRejectedValueOnce(new Error('offline'));else api.load.mockResolvedValue(updated)
 fireEvent.click(screen.getByRole('button',{name:'Save'}));await waitFor(()=>expect(screen.queryByRole('dialog',{name:'Change Location'})).toBeNull());expect(api.rpc).toHaveBeenCalledOnce();expect(api.rpc.mock.calls[0]).toEqual(['move_physical_bottles',expect.objectContaining({p_bottle_ids:['bottle'],p_from_location_id:'rack',p_to_location_id:'other'})]);if(refreshFails){api.load.mockResolvedValue(updated);fireEvent.click(screen.getAllByRole('button',{name:'Retry Refresh'})[0]);await waitFor(()=>expect(screen.queryAllByRole('button',{name:'Retry Refresh'})).toHaveLength(0))}expect(screen.getByRole('dialog').textContent).toContain('Other Rack');fireEvent.click(screen.getByRole('button',{name:'Back'}));await waitFor(()=>expect(screen.queryByRole('dialog')).toBeNull());expect((screen.getByLabelText('Search the cellar') as HTMLInputElement).value).toBe('Test');expect(window.confirm).not.toHaveBeenCalled()
})
