// @vitest-environment jsdom
import {afterEach,beforeEach,expect,it,vi} from 'vitest'
import {cleanup,fireEvent,render,screen,waitFor,within} from '@testing-library/react'
import {InventoryAudit} from './InventoryAudit'
import {EMPTY_CELLAR_DATA,type CellarData} from './lib/cellar-data'
import {auditSummary,type InventoryAudit as Audit,type AuditLocation} from './lib/inventory-audit'
const api=vi.hoisted(()=>({rpc:vi.fn()}));vi.mock('./lib/supabase',()=>({supabase:{rpc:api.rpc}}))
vi.mock('./AcquisitionModal',()=>({AcquisitionModal:(props:{auditMode:boolean;onComplete:(v:unknown)=>void})=><div><p>Existing simplified wine entry {String(props.auditMode)}</p><button onClick={()=>props.onComplete({result:{wine_ids:['new']},refreshFailed:false})}>Save New Wine</button></div>}))
const bottle=(id:string,aging=false)=>({id,wineId:'w',purchaseItemId:'i',storageLocationId:'rack',status:'active',isAging:aging,effectiveHoldUntilYear:aging?2035:null})
const data={...EMPTY_CELLAR_DATA,wines:[{id:'w',name:'Riesling',wineryName:'Forge',vintage:2023,availableQuantity:3,storageNames:['Rack']},{id:'other',name:'Cider',wineryName:'Orchard',vintage:2024,availableQuantity:1,storageNames:['Wall']},{id:'new',name:'New Red',wineryName:'New Winery',availableQuantity:0,storageNames:[]}],locations:[{id:'rack',name:'Rack',isActive:true},{id:'wall',name:'Wall',isActive:true}],purchaseItems:[{id:'i',wineId:'w',purchaseId:'p'},{id:'i2',wineId:'other',purchaseId:'p2'}],purchases:[{id:'p',acquisitionDate:'2026-09-05'},{id:'p2',acquisitionDate:'2026-09-06'}],bottles:[bottle('b1'),bottle('b2'),bottle('b3',true),{...bottle('outside',true),wineId:'other',purchaseItemId:'i2',storageLocationId:'wall'}]} as unknown as CellarData
let audit:Audit;let locations:AuditLocation[];const refresh=vi.fn(),notice=vi.fn()
function reset(){audit={id:'a',location_id:'rack',status:'counting',snapshot:data.bottles.filter(b=>b.storageLocationId==='rack').map(b=>({id:b.id,wine_id:b.wineId,purchase_item_id:b.purchaseItemId,location_id:'rack',is_aging:b.isAging,hold:b.effectiveHoldUntilYear,updated_at:'2026-09-10'})),observations:{},revision:0,applied_at:null,created_at:'2026-09-10'};locations=[{id:'rack',name:'Rack',active_audit:null,last_audit:null,changed_since_audit:false},{id:'wall',name:'Wall',active_audit:null,last_audit:null,changed_since_audit:false}]}
beforeEach(()=>{vi.clearAllMocks();localStorage.clear();sessionStorage.clear();reset();refresh.mockResolvedValue(undefined);api.rpc.mockImplementation(async(name,args)=>{if(name==='inventory_audit_locations')return {data:locations,error:null};const p=args.p_payload;if(args.p_action==='observe'){audit={...audit,revision:audit.revision+1,observations:{...audit.observations,[p.wine_id]:{...p.observation,moves:p.observation.move_ids.map((id:string)=>({id,location_id:'wall'}))}}}}if(args.p_action==='apply'){audit={...audit,status:'applied',applied_at:'2026-09-10T12:00:00Z'};locations[0]={...locations[0],active_audit:null,last_audit:audit}}else if(args.p_action==='cancel'){audit={...audit,status:'cancelled'};locations[0].active_audit=null}else locations[0].active_audit=audit;return {data:audit,error:null}})})
afterEach(cleanup)
const mount=(editable=true)=>render(<InventoryAudit householdId="h" data={data} photoUrls={{}} editable={editable} onSaved={refresh} onNotice={notice}/>);
const start=async()=>{await screen.findAllByRole('button',{name:'Start Audit'});fireEvent.click(screen.getAllByRole('button',{name:'Start Audit'})[0]);await screen.findByRole('button',{name:'✓ Correct'})}
it('starts one location, confirms expected in one action and applies once with independent status',async()=>{mount();await start();expect(screen.queryByRole('heading',{name:'Cider'})).toBeNull();fireEvent.click(screen.getByRole('button',{name:'✓ Correct'}));await screen.findByRole('button',{name:'Apply Audit'});expect(auditSummary(audit)).toMatchObject({confirmed:1,expected:3,correct:3});fireEvent.click(await screen.findByRole('button',{name:'Apply Audit'}));await screen.findByText(/Audited Sep 10/);expect(screen.queryByRole('button',{name:'Apply Audit'})).toBeNull();expect(api.rpc.mock.calls.filter(c=>c[1]?.p_action==='apply')).toHaveLength(1);expect(locations[1].last_audit).toBeNull()})
it('stages shortage without inventory calls and requires meaningful Aging selection',async()=>{mount();await start();fireEvent.click(screen.getByRole('button',{name:'Decrease physical count'}));fireEvent.click(screen.getByRole('button',{name:'Confirm Count'}));await screen.findByRole('alert');expect(api.rpc.mock.calls.some(c=>c[1]?.p_action==='observe')).toBe(false);const missing=screen.getByText('Which 1 bottle is missing?').parentElement!;fireEvent.change(within(missing).getAllByRole('combobox')[0],{target:{value:'1'}});fireEvent.click(screen.getByRole('button',{name:'Confirm Count'}));await screen.findByRole('button',{name:'Apply Audit'});expect(audit.observations.w.remove_ids).toEqual(['b1']);expect(audit.observations.w.actual).toBe(2);expect(api.rpc.mock.calls.every(c=>['inventory_audit_locations','inventory_audit_command'].includes(c[0]))).toBe(true)})
it('Bottle Not Listed finds existing wine elsewhere and stages its Aging bottle Move Here',async()=>{mount();await start();fireEvent.click(screen.getByRole('button',{name:'+ Bottle Not Listed'}));fireEvent.change(await screen.findByLabelText('Search existing wines'),{target:{value:'Cider'}});fireEvent.click(screen.getByRole('button',{name:/Orchard · Cider/}));await screen.findByRole('heading',{name:'Cider'});fireEvent.change(screen.getByRole('combobox',{name:/Move here from/}),{target:{value:'1'}});fireEvent.change(screen.getByLabelText('Physical count'),{target:{value:'1'}});fireEvent.click(screen.getByRole('button',{name:'Confirm Count'}));await waitFor(()=>expect(audit.observations.other.confirmed).toBe(true));expect(audit.observations.other.moves[0].id).toBe('outside');expect(auditSummary(audit).moves).toBe(1)})
it('Save & Pause persists an unfinished count and Resume restores it',async()=>{mount();await start();fireEvent.click(screen.getByRole('button',{name:'Increase physical count'}));fireEvent.click(screen.getByRole('button',{name:/Locations.*Save & Pause/}));await screen.findByRole('button',{name:'Resume Audit'});expect(audit.observations.w.actual).toBe(4);expect(audit.observations.w.confirmed).toBe(false);fireEvent.click(screen.getByRole('button',{name:'Resume Audit'}));await screen.findByLabelText('Physical count');expect((screen.getByLabelText('Physical count') as HTMLInputElement).value).toBe('4')})
it('leaving the screen preserves unconfirmed local count without a false unsaved warning',async()=>{const view=mount();await start();fireEvent.click(screen.getByRole('button',{name:'Decrease physical count'}));view.unmount();mount();await screen.findByRole('button',{name:'Resume Audit'});fireEvent.click(screen.getByRole('button',{name:'Resume Audit'}));await screen.findByLabelText('Physical count');expect((screen.getByLabelText('Physical count') as HTMLInputElement).value).toBe('2')})
it('reuses Add Wine in identity-only audit mode and returns to the active count',async()=>{mount();await start();fireEvent.click(screen.getByRole('button',{name:'+ Bottle Not Listed'}));fireEvent.click(await screen.findByRole('button',{name:'Add a New Wine'}));await screen.findByText('Existing simplified wine entry true');fireEvent.click(screen.getByRole('button',{name:'Save New Wine'}));await screen.findByRole('heading',{name:'New Red'});expect(screen.queryByRole('button',{name:'Save New Wine'})).toBeNull();expect((screen.getByLabelText('Physical count') as HTMLInputElement).value).toBe('0')})
it('cancel requires confirmation and never invokes inventory apply',async()=>{const confirm=vi.spyOn(window,'confirm').mockReturnValue(false);mount();await start();fireEvent.click(screen.getByRole('button',{name:'Cancel Audit'}));expect(api.rpc.mock.calls.some(c=>c[1]?.p_action==='cancel')).toBe(false);confirm.mockReturnValue(true);fireEvent.click(screen.getByRole('button',{name:'Cancel Audit'}));await screen.findAllByRole('button',{name:'Start Audit'});expect(api.rpc.mock.calls.some(c=>c[1]?.p_action==='apply')).toBe(false);confirm.mockRestore()})
it('lost acknowledgement retries the identical command and successful Apply/failed refresh cannot apply twice',async()=>{mount();await start();api.rpc.mockResolvedValueOnce({error:{message:'Connection lost'}});fireEvent.click(screen.getByRole('button',{name:'✓ Correct'}));await screen.findByRole('button',{name:'Retry safely'});const first=api.rpc.mock.calls.at(-1);fireEvent.click(screen.getByRole('button',{name:'Retry safely'}));await waitFor(()=>expect(audit.observations.w?.confirmed).toBe(true));const calls=api.rpc.mock.calls.filter(c=>c[1]?.p_action==='observe');expect(calls).toHaveLength(2);expect(calls[1]).toEqual(first);fireEvent.click(screen.getByRole('button',{name:'Review Audit'}));refresh.mockRejectedValueOnce(new Error('offline'));fireEvent.click(await screen.findByRole('button',{name:'Apply Audit'}));await screen.findByRole('button',{name:'Retry Refresh'});expect(screen.queryByRole('button',{name:'Apply Audit'})).toBeNull()})
it('viewers see location results but no mutation controls',async()=>{mount(false);await screen.findByRole('heading',{name:'Rack'});expect(screen.queryByRole('button',{name:'Start Audit'})).toBeNull()})

it('changing a previously confirmed count then opening review persists it as unconfirmed',async()=>{mount();await start();fireEvent.click(screen.getByRole('button',{name:'✓ Correct'}));await screen.findByRole('button',{name:'Apply Audit'});fireEvent.click(screen.getByRole('button',{name:'Back to Counting'}));fireEvent.click(screen.getByRole('button',{name:'Increase physical count'}));fireEvent.click(screen.getByRole('button',{name:'Review Audit'}));await screen.findByRole('button',{name:'Count this wine'});expect(audit.observations.w.confirmed).toBe(false);expect(audit.observations.w.actual).toBe(4);expect((screen.getByRole('button',{name:'Apply Audit'}) as HTMLButtonElement).disabled).toBe(true)})
it('zero count proposes missing bottles without fabricating a historical explanation',async()=>{mount();await start();fireEvent.change(screen.getByLabelText('Physical count'),{target:{value:'0'}});fireEvent.click(screen.getByRole('button',{name:'Confirm Count'}));await screen.findByRole('button',{name:'Apply Audit'});expect(audit.observations.w.actual).toBe(0);expect(audit.observations.w.remove_ids).toEqual(['b1','b2','b3']);expect(audit.observations.w.reason).toBe('Not sure')})
