import { useEffect, useRef, useState } from 'react'
import type { CellarData } from './lib/cellar-data'
import { supabase } from './lib/supabase'
import { createUniqueId } from './lib/unique-id'
import type { NoticeTone } from './lib/interaction'
import { PhotoImage } from './PhotoImage'
import { AcquisitionModal } from './AcquisitionModal'
import { auditWines, expectedBottles, auditSummary, auditDelta, auditBottleGroups, type InventoryAudit as Audit, type AuditLocation } from './lib/inventory-audit'
import { displayDate } from './lib/presentation'

type Draft = { actual:number;reason:string;remove_ids:string[];move_ids:string[] }
const defaultObservation = (audit:Audit,id:string):Draft => { const o=audit.observations[id];return {actual:o?.actual??expectedBottles(audit,id).length,reason:o?.reason??'Not sure',remove_ids:o?.remove_ids??[],move_ids:o?.moves.map(b=>b.id)??[]} }
export function InventoryAudit({householdId,data,photoUrls,editable,onSaved,onNotice,onBusy}: {householdId:string;data:CellarData;photoUrls:Record<string,string>;editable:boolean;onBusy?:(busy:boolean)=>void;onSaved:()=>Promise<void>;onNotice:(s:string,t?:NoticeTone)=>void}) {
 const [locations,setLocations]=useState<AuditLocation[]>([]),[audit,setAudit]=useState<Audit|null>(null),[wineId,setWineId]=useState('')
 const [search,setSearch]=useState(''),[sort,setSort]=useState('winery'),[review,setReview]=useState(false),[unlisted,setUnlisted]=useState(false),[adding,setAdding]=useState(false)
 const [busy,setBusy]=useState(false),[error,setError]=useState(''),[loaded,setLoaded]=useState(false),[refreshFailed,setRefreshFailed]=useState(false)
 const [draft,setDraft]=useState<Draft>({actual:0,reason:'Not sure',remove_ids:[],move_ids:[]})
 const flight=useRef(false), pending=useRef<{id:string;action:string;payload:Record<string,unknown>}|null>(null)
 useEffect(()=>{onBusy?.(busy);return()=>onBusy?.(false)},[busy,onBusy])
 const localKey=(a:Audit,id:string)=>`cellar.audit.${householdId}.${a.id}.${id}`
 const readDraft=(a:Audit,id:string)=> { try {const raw=localStorage.getItem(localKey(a,id));if(raw){const v=JSON.parse(raw);if(v.baseline===JSON.stringify([expectedBottles(a,id),a.observations[id]]))return v.draft as Draft}}catch{/* server observation remains authoritative */}return defaultObservation(a,id) }
 const selectWine=(a:Audit,id:string)=>{setWineId(id);setDraft(readDraft(a,id));setReview(false);setUnlisted(false);sessionStorage.setItem(`cellar.audit.position.${a.id}`,id)}
 const load=async()=> { if(!supabase)return;const r=await supabase.rpc('inventory_audit_locations',{p_household_id:householdId});if(r.error)throw new Error(r.error.message);setLocations(r.data??[]);setLoaded(true);return r.data as AuditLocation[] }
 useEffect(()=>{void load().catch(e=>setError(e.message))},[householdId])
 const change=(patch:Partial<Draft>)=>{const next={...draft,...patch};setDraft(next);if(audit&&wineId)localStorage.setItem(localKey(audit,wineId),JSON.stringify({baseline:JSON.stringify([expectedBottles(audit,wineId),audit.observations[wineId]]),draft:next}))}
 const open=(a:Audit)=>{setAudit(a);setSearch('');setReview(a.status==='applied');setUnlisted(false);const saved=sessionStorage.getItem(`cellar.audit.position.${a.id}`);const id=saved&&auditWines(a).includes(saved)?saved:auditWines(a).find(id=>!a.observations[id]?.confirmed)??auditWines(a)[0]??'';setWineId(id);setDraft(readDraft(a,id));setError('')}
 const command=async(action:string,payload:Record<string,unknown>={},target=audit):Promise<Audit|null>=>{
  if(!supabase||flight.current||!editable)return null
  flight.current=true;setBusy(true);setError('')
  if(!pending.current)pending.current={id:target?.id??createUniqueId(),action,payload:{...payload,revision:target?.revision??0,request_id:createUniqueId()}}
  const request=pending.current
  try {const r=await supabase.rpc('inventory_audit_command',{p_household_id:householdId,p_audit_id:request.id,p_action:request.action,p_payload:request.payload});if(r.error){if(/^[0-9A-Z]{5}$/.test(r.error.code??''))pending.current=null;throw new Error(r.error.message)}
   pending.current=null;const a=r.data as Audit;setAudit(a);return a
  }catch(e){setError(e instanceof Error?e.message:'Could not save the audit. Retry safely.');return null}finally{flight.current=false;setBusy(false)}
 }
 const resume=async(l:AuditLocation)=>{if(l.active_audit){open(l.active_audit);return}const a=await command('start',{location_id:l.id},null);if(a)open(a)}
 const wine=data.wines.find(w=>w.id===wineId), name=(id:string)=>{const w=data.wines.find(w=>w.id===id);return [w?.wineryName,w?.name,w?.nonVintage?'NV':w?.vintage].filter(Boolean).join(' · ')||'Wine'}
 const matches=(id:string)=>name(id).toLowerCase().includes(search.trim().toLowerCase())
 const ids=audit?auditWines(audit).sort((a,b)=>sort==='wine'?(data.wines.find(w=>w.id===a)?.name??'').localeCompare(data.wines.find(w=>w.id===b)?.name??''):name(a).localeCompare(name(b))):[]
 const expected=audit?expectedBottles(audit,wineId):[], missing=Math.max(0,expected.length+draft.move_ids.length-draft.actual)
 const groups=auditBottleGroups(expected,data)
 const removed=missing===0?[]:groups.length<=1||missing===expected.length?expected.slice(0,missing).map(b=>b.id):draft.remove_ids
 const outside=data.bottles.filter(b=>b.wineId===wineId&&b.status==='active'&&b.storageLocationId!==audit?.location_id)
 const outsideGroups=auditBottleGroups(outside.map(b=>({id:b.id,wine_id:b.wineId,purchase_item_id:b.purchaseItemId,location_id:b.storageLocationId,is_aging:b.isAging,hold:b.effectiveHoldUntilYear,updated_at:''})),data)
 const summary=audit?auditSummary(audit):null, location=locations.find(l=>l.id===audit?.location_id)
 const confirm=async()=>{if(!audit)return;if(removed.length!==missing){setError('Choose which bottles are missing so Aging and purchase history stay with the right bottles.');return}
  const a=await command('observe',{wine_id:wineId,observation:{...draft,remove_ids:removed,confirmed:true}})
  if(a){localStorage.removeItem(localKey(a,wineId));setDraft(defaultObservation(a,wineId));const next=ids.find(id=>id!==wineId&&!a.observations[id]?.confirmed);if(next)selectWine(a,next);else {setReview(true);setSearch('')}}
 }
 const persistDraft=async():Promise<Audit|null>=>{
  if(!audit||audit.status!=='counting'||!wineId)return audit
  if(JSON.stringify(defaultObservation(audit,wineId))===JSON.stringify(draft))return audit
  const a=await command('observe',{wine_id:wineId,observation:{...draft,remove_ids:removed,confirmed:false}})
  if(a)localStorage.removeItem(localKey(a,wineId));return a
 }
 const navigateWine=async(id:string)=>{const a=await persistDraft();if(a)selectWine(a,id)}
 const goReview=async()=>{const a=await persistDraft();if(a){setReview(true);setUnlisted(false)}}
 const goUnlisted=async()=>{const a=await persistDraft();if(a){setUnlisted(true);setReview(false);setSearch('')}}
 const savePause=async()=>{if(!await persistDraft())return;setAudit(null);setWineId('');await load().catch(e=>setError(e.message))}
 const addExisting=async(id:string)=>{const current=await persistDraft();if(!current)return;if(auditWines(current).includes(id)){selectWine(current,id);return}const a=await command('observe',{wine_id:id,observation:{actual:0,confirmed:false,reason:'Not sure',remove_ids:[],move_ids:[]}},current);if(a){selectWine(a,id);const next={...defaultObservation(a,id),actual:0};setDraft(next)}}
 const retryRefresh=async()=>{setError('');try{await onSaved();const ls=await load();if(audit){const l=ls?.find(l=>l.id===audit.location_id);const a=l?.active_audit??l?.last_audit;if(a)open(a)}setRefreshFailed(false)}catch(e){setError(e instanceof Error?e.message:'Refresh failed')}}
 const apply=async()=>{const a=await command('apply');if(a){setReview(true);onNotice('Audit applied. This location is reconciled.','success');try{await onSaved();await load()}catch{setRefreshFailed(true);onNotice('Saved, but the screen could not refresh.','warning')}}}
 const alert=<>{error&&<div className="form-message error" role="alert"><p>{error}</p>{pending.current?<button className="secondary-button" disabled={busy} onClick={async()=>{const action=pending.current?.action;const a=await command('retry');if(a){open(a);if(action==='apply'){await retryRefresh()}else await load().catch(e=>setError(e.message))}}}>Retry safely</button>:<button className="secondary-button" disabled={busy} onClick={()=>void retryRefresh()}>Retry / Refresh</button>}{audit?.status==='counting'&&!pending.current&&<button className="secondary-button" disabled={busy} onClick={async()=>{const a=await command('refresh');if(a){open(a);await onSaved().catch(()=>setRefreshFailed(true));onNotice('Current inventory loaded. Reconfirm changed wines.')}}}>Refresh counts</button>}</div>}{refreshFailed&&<p role="alert">Saved, but the screen could not refresh. <button className="secondary-button" onClick={()=>void retryRefresh()}>Retry Refresh</button></p>}</>
 if(!audit)return <section className="inventory-audit"><p>Pick one location. Count what is physically here, then review and apply corrections.</p>{alert}{!loaded&&!error&&<p>Loading locations…</p>}{locations.map(l=><article className="audit-location" key={l.id}><h3>{l.name}</h3><p>{l.active_audit?`${auditSummary(l.active_audit).confirmed} of ${auditSummary(l.active_audit).wines} wines confirmed`:l.last_audit?`Audited ${displayDate(l.last_audit.applied_at!)}${l.changed_since_audit?' · Inventory changed since audit':''}`:'Not audited'}</p><div className="audit-actions">{editable&&<button className="primary-button" disabled={busy} onClick={()=>void resume(l)}>{l.active_audit?'Resume Audit':'Start Audit'}</button>}{l.last_audit&&<button className="secondary-button" onClick={()=>open(l.last_audit!)}>View Results</button>}</div></article>)}</section>
 return <section className="inventory-audit" aria-busy={busy}>
  <div className="audit-context"><button className="text-button" disabled={busy||Boolean(pending.current)} onClick={()=>void savePause()}>‹ Locations / Save & Pause</button><h3>{location?.name} Audit</h3><p>{audit.status==='applied'?`Audited ${displayDate(audit.applied_at!)}`:`${summary!.confirmed} of ${summary!.wines} wines confirmed · ${summary!.expected} expected bottles`}</p></div>
  {alert}
  {audit.status==='counting'&&<><p className="audit-hint">Counts are proposals. Confirm saves progress; Save & Pause also saves an unfinished count.</p><div className="audit-actions"><button className="secondary-button" disabled={busy} onClick={()=>void goUnlisted()}>+ Bottle Not Listed</button><button className="secondary-button" disabled={busy} onClick={()=>void goReview()}>Review Audit</button></div></>}
  {unlisted?<><label>Search existing wines<input type="search" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Winery, wine or vintage"/></label><div className="audit-search-results">{data.wines.filter(w=>matches(w.id)).slice(0,30).map(w=><button className="audit-result" disabled={busy} key={w.id} onClick={()=>void addExisting(w.id)}>{name(w.id)}<small>{w.availableQuantity} in Cellar{w.storageNames?.length?` · ${w.storageNames.join(', ')}`:''}</small></button>)}</div>{!data.wines.some(w=>matches(w.id))&&<p>No matching wine. Add its identity below; its bottles will stay proposed until Apply Audit.</p>}<button className="primary-button" disabled={busy} onClick={()=>setAdding(true)}>Add a New Wine</button></>:
   review?<><div className="audit-summary"><p><strong>{summary!.expected}</strong> expected bottles · <strong>{summary!.correct}</strong> confirmed correctly</p><p>{summary!.discrepancies} quantity discrepancies · {summary!.moves} location corrections · {summary!.unlisted} unlisted wines</p></div>{ids.filter(id=>!audit.observations[id]?.confirmed||auditDelta(audit,id)!==0||audit.observations[id]?.moves.length).map(id=>{const o=audit.observations[id];return <article className="audit-exception" key={id}><h4>{name(id)}</h4><p>Expected {expectedBottles(audit,id).length} → Physical {o?.actual??'Not confirmed'}</p>{o?.moves.length>0&&<p>Move {o.moves.length} here</p>}{auditDelta(audit,id)!==0&&<p>Inventory correction: {auditDelta(audit,id)>0?'+':''}{auditDelta(audit,id)} · {o?.reason}</p>}{audit.status==='counting'&&<button className="secondary-button" disabled={busy} onClick={()=>void navigateWine(id)}>{o?.confirmed?'Change count':'Count this wine'}</button>}</article>})}{audit.status==='counting'&&<><p>{summary!.confirmed===summary!.wines?'Review the exceptions above. Apply saves all corrections together.':'Confirm the remaining wines before applying.'}</p><button className="primary-button" disabled={busy||Boolean(pending.current)||summary!.confirmed!==summary!.wines} onClick={()=>void apply()}>{busy?'Applying…':'Apply Audit'}</button><button className="secondary-button" onClick={()=>setReview(false)}>Back to Counting</button></>}</>:
   <><div className="audit-search"><label>Search this location<input type="search" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Winery, wine or vintage"/></label><label>Sort<select value={sort} onChange={e=>setSort(e.target.value)}><option value="winery">Winery</option><option value="wine">Wine name</option></select></label></div>{search?<div className="audit-search-results">{ids.filter(matches).map(id=><button className="audit-result" key={id} onClick={async()=>{await navigateWine(id);setSearch('')}}>{name(id)}{audit.observations[id]?.confirmed?' ✓':''}</button>)}{!ids.some(matches)&&<p>No match in this location. Use Bottle Not Listed to search the collection.</p>}</div>:null}
   {wine&&<article className="audit-counter" key={wineId}><div className="audit-wine-identity">{data.photos.find(p=>p.wineId===wineId)&&<PhotoImage src={photoUrls[(data.photos.find(p=>p.wineId===wineId&&p.isHero)??data.photos.find(p=>p.wineId===wineId))!.id]} alt="Wine"/>}<div><p>{wine.wineryName}</p><h3>{wine.name}</h3><p>{wine.nonVintage?'NV':wine.vintage??'Vintage not recorded'}</p></div></div><p>Expected: <strong>{expected.length}</strong>{expected.some(b=>b.is_aging)?` · ${expected.filter(b=>b.is_aging).length} Aging`:''}</p>
    <fieldset disabled={busy||Boolean(pending.current)} className="workflow-fields"><div className="audit-stepper"><button className="secondary-button" aria-label="Decrease physical count" disabled={draft.actual===0} onClick={()=>change({actual:Math.max(0,draft.actual-1)})}>−</button><label>Physical count<input type="number" inputMode="numeric" min="0" max="1000" value={draft.actual} onChange={e=>change({actual:Math.max(0,Math.min(1000,Math.trunc(Number(e.target.value))))})}/></label><button className="secondary-button" aria-label="Increase physical count" onClick={()=>change({actual:Math.min(1000,draft.actual+1)})}>+</button></div>
    {outsideGroups.length>0&&<details><summary>Found Here / Move Here</summary><p>If these are bottles already listed elsewhere, move them here instead of adding inventory.</p>{outsideGroups.map(g=><label key={g.ids[0]}>{g.label}<select aria-label={`Move here from ${g.label}`} value={g.ids.filter(id=>draft.move_ids.includes(id)).length} onChange={e=>{const prev=g.ids.filter(id=>draft.move_ids.includes(id)).length,n=Number(e.target.value);change({move_ids:[...draft.move_ids.filter(id=>!g.ids.includes(id)),...g.ids.slice(0,n)],actual:Math.max(0,draft.actual+n-prev)})}}>{Array.from({length:g.ids.length+1},(_,i)=><option key={i} value={i}>{i===0?'None':`Move ${i} here`}</option>)}</select></label>)}</details>}
    {missing>0&&groups.length>1&&missing!==expected.length&&<div className="audit-missing"><p>Which {missing} {missing===1?'bottle is':'bottles are'} missing?</p>{groups.map(g=><label key={g.ids[0]}>{g.label}<select value={g.ids.filter(id=>draft.remove_ids.includes(id)).length} onChange={e=>change({remove_ids:[...draft.remove_ids.filter(id=>!g.ids.includes(id)),...g.ids.slice(0,Number(e.target.value))]})}>{Array.from({length:g.ids.length+1},(_,i)=><option key={i} value={i}>{i} missing</option>)}</select></label>)}</div>}
    {(draft.actual!==expected.length||draft.move_ids.length>0)&&<><p>Proposed: {draft.move_ids.length>0?`Move ${draft.move_ids.length} here. `:''}{draft.actual-expected.length-draft.move_ids.length!==0?`${draft.actual-expected.length-draft.move_ids.length>0?'+':''}${draft.actual-expected.length-draft.move_ids.length} inventory correction.`:''}</p><label>Reason (optional)<select value={draft.reason} onChange={e=>change({reason:e.target.value})}>{['Not sure','Inventory correction',...(draft.actual<expected.length?['Unlogged consumption','Gifted but not logged']:['Unlogged acquisition','Gift received'])].map(r=><option key={r}>{r}</option>)}</select></label></>}
    <button className="primary-button audit-confirm" onClick={()=>void confirm()}>{busy?'Saving count…':draft.actual===expected.length&&!draft.move_ids.length?'✓ Correct':'Confirm Count'}</button></fieldset>
   </article>}{!wine&&<p>No bottles expected here. Use Bottle Not Listed or review this empty location.</p>}<details><summary>All wines in this location</summary>{ids.map(id=><button className="audit-result" disabled={busy} key={id} onClick={()=>void navigateWine(id)}>{name(id)}{audit.observations[id]?.confirmed?' ✓':''}</button>)}</details></>}
  {audit.status==='counting'&&<button className="text-button audit-cancel" disabled={busy||Boolean(pending.current)} onClick={async()=>{if(window.confirm('Discard this unfinished audit? Inventory will not change.')){const a=await command('cancel');if(a){setAudit(null);await load().catch(e=>setError(e.message))}}}}>Cancel Audit</button>}
  {adding&&<AcquisitionModal auditMode action="add-wine" householdId={householdId} data={data} initialLocationId={audit.location_id} onClose={()=>setAdding(false)} onSaved={onSaved} onNotice={onNotice} onComplete={async c=>{setAdding(false);if(c.refreshFailed)setRefreshFailed(true);if(c.retryPhoto)onNotice('Wine saved; photo not added. Add its photo later from Wine Detail.','warning');await addExisting(c.result.wine_ids[0])}}/>}
 </section>
}
