import { FormEvent, useEffect, useMemo, useRef, useState } from 'react'
import type { CellarData, GiftRecord, OpeningRecord, PhotoRecord, PurchaseRecord, VisitRecord, WineRecord, WineryRecord } from './lib/cellar-data'
import { supabase } from './lib/supabase'
import { createUniqueId } from './lib/unique-id'
import { StateSelect } from './StateSelect'
import { ClosureSelect } from './ClosureSelect'
import { EnrichmentDashboard, RecordEnrichment } from './Enrichment'
import { userError, validatePhoto } from './lib/user-error'
import { guidanceSourceLabel, guidanceStatus } from './lib/aging-guidance'

export type ManagementTarget =
  | { kind: 'wine'; record: WineRecord; initialTab?: DetailTab; autoAddPhoto?: boolean }
  | { kind: 'winery'; record: WineryRecord; initialTab?: DetailTab; autoAddPhoto?: boolean }
  | { kind: 'opening'; record: OpeningRecord; initialTab?: DetailTab; autoAddPhoto?: boolean }
  | { kind: 'purchase'; record: PurchaseRecord; initialTab?: DetailTab; autoAddPhoto?: boolean }
  | { kind: 'gift'; record: GiftRecord; initialTab?: DetailTab; autoAddPhoto?: boolean }
  | { kind: 'visit'; record: VisitRecord; initialTab?: DetailTab; autoAddPhoto?: boolean }
  | { kind: 'history' | 'favorites' | 'statistics' | 'storage' | 'documents' | 'trips' | 'enrichment' | 'settings' }

type DetailTab = 'details' | 'history' | 'photos'

const optional = (form: FormData, key: string) => String(form.get(key) ?? '').trim() || null
const numberOrNull = (form: FormData, key: string) => { const value = optional(form, key); return value === null ? null : Number(value) }
const safeName = (value: string) => value.replace(/[^a-zA-Z0-9._-]/g, '_')
const date = (value: string) => new Intl.DateTimeFormat('en-US', { month: 'short', day: 'numeric', year: 'numeric' }).format(new Date(value.length === 10 ? `${value}T12:00:00` : value))
const money = (value: number) => new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD' }).format(value)
const targetKey = (target: ManagementTarget) => 'record' in target ? `${target.kind}:${target.record.id}:${target.initialTab ?? 'details'}:${target.autoAddPhoto ? 'add-photo' : ''}` : target.kind

function targetTitle(target: ManagementTarget, data: CellarData) {
  if (target.kind === 'wine' || target.kind === 'winery') return target.record.name
  if (target.kind === 'opening') return data.wines.find((wine) => wine.id === target.record.wineId)?.name ?? 'Bottle opening'
  if (target.kind === 'purchase') return target.record.purchaseLocation ?? 'Purchase'
  if (target.kind === 'gift') return `Gift to ${target.record.giftedTo}`
  if (target.kind === 'visit') return data.wineries.find((winery) => winery.id === target.record.wineryId)?.name ?? 'Winery visit'
  return ({ history: 'History', favorites: 'Favorites', statistics: 'Statistics', storage: 'Storage', documents: 'Documents & Receipts', trips: 'Trips', enrichment: 'Data Enrichment', settings: 'Settings' } as Record<string, string>)[target.kind]
}

function photosFor(target: ManagementTarget, data: CellarData) {
  return data.photos.filter((photo) => {
    if (target.kind === 'wine') return photo.wineId === target.record.id
    if (target.kind === 'winery') return photo.wineryId === target.record.id
    if (target.kind === 'opening') return photo.openingId === target.record.id
    if (target.kind === 'purchase') return photo.purchaseId === target.record.id
    if (target.kind === 'visit') return photo.wineryVisitId === target.record.id
    return false
  })
}

export function ManagementModal({ target, householdId, data, photoUrls, editable, canGoBack, returnToEnrichment, onBack, onClose, onNavigate, onSaved, onOpenBottle }: {
  target: ManagementTarget; householdId: string; data: CellarData; photoUrls: Record<string, string>; editable: boolean; canGoBack: boolean; returnToEnrichment: boolean; onBack: () => void; onClose: () => void; onNavigate: (target: ManagementTarget) => void; onSaved: () => Promise<void>; onOpenBottle: (wineId: string) => void
}) {
  const [tab, setTab] = useState<DetailTab>('details')
  const [editing, setEditing] = useState(false)
  const [busy, setBusy] = useState(false)
  const [message, setMessage] = useState('')
  const [viewer, setViewer] = useState<PhotoRecord | null>(null)
  const [photoPrompt, setPhotoPrompt] = useState(false)
  const [enrichmentKind, setEnrichmentKind] = useState<'wine' | 'winery'>(() => sessionStorage.getItem('cellar.enrichment.kind') === 'winery' ? 'winery' : 'wine')
  const [enrichmentFilter, setEnrichmentFilter] = useState(() => sessionStorage.getItem('cellar.enrichment.filter') || 'all')
  const modalRef = useRef<HTMLElement | null>(null)
  const enrichmentScroll = useRef(Number(sessionStorage.getItem('cellar.enrichment.scroll') || 0))
  useEffect(() => { sessionStorage.setItem('cellar.enrichment.kind', enrichmentKind) }, [enrichmentKind])
  useEffect(() => { sessionStorage.setItem('cellar.enrichment.filter', enrichmentFilter) }, [enrichmentFilter])
  useEffect(() => {
    setTab('record' in target ? target.initialTab ?? 'details' : 'details'); setEditing(false); setMessage(''); setViewer(null); setPhotoPrompt('record' in target && Boolean(target.autoAddPhoto))
    if (target.kind === 'enrichment') requestAnimationFrame(() => { if (modalRef.current) modalRef.current.scrollTop = enrichmentScroll.current })
  }, [targetKey(target)])
  useEffect(() => {
    const closeViewer = () => setViewer(null)
    window.addEventListener('popstate', closeViewer)
    return () => window.removeEventListener('popstate', closeViewer)
  }, [])
  const viewPhoto = (photo: PhotoRecord) => {
    setViewer(photo)
    window.history.pushState({ ...window.history.state, cellarLightbox: true }, '')
  }
  const closeViewer = () => window.history.back()
  const recordTarget = ['wine', 'winery', 'opening', 'purchase', 'gift', 'visit'].includes(target.kind)
  const tabbedRecordTarget = target.kind !== 'gift'
  const relatedPhotos = photosFor(target, data)
  const hero = relatedPhotos.find((photo) => photo.isHero) ?? relatedPhotos[0]
  const title = targetTitle(target, data)
  const usesBack = recordTarget || canGoBack
  return <div className="modal-backdrop" onMouseDown={(event) => event.target === event.currentTarget && !busy && onClose()}>
    <section ref={modalRef} className="workflow-modal workflow-form-modal management-modal" role="dialog" aria-modal="true" aria-label={title} onScroll={(event) => { if (target.kind === 'enrichment') { enrichmentScroll.current = event.currentTarget.scrollTop; sessionStorage.setItem('cellar.enrichment.scroll', String(event.currentTarget.scrollTop)) } }}>
      <div className="sheet-header detail-header">
        <button className="icon-close" onClick={usesBack ? onBack : onClose} aria-label={usesBack ? 'Back' : 'Close'}>{usesBack ? '‹' : '×'}</button>
        <div><p className="eyebrow burgundy">THE CELLAR</p><h2>{title}</h2></div>
        {recordTarget && editable && (target.kind === 'wine' || target.kind === 'winery') ? <button className="text-button" onClick={() => setEditing((value) => !value)}>{editing ? 'Cancel' : 'Edit'}</button> : <span className="header-spacer" />}
      </div>
      {recordTarget && tabbedRecordTarget && <div className="detail-tabs"><button className={tab === 'details' ? 'active' : ''} onClick={() => setTab('details')}>Details</button><button className={tab === 'history' ? 'active' : ''} onClick={() => setTab('history')}>History</button><button className={tab === 'photos' ? 'active' : ''} onClick={() => setTab('photos')}>Photos</button></div>}
      {recordTarget && tab === 'details' && <>
        <RecordHero target={target} data={data} hasPhoto={Boolean(hero)} url={hero ? photoUrls[hero.id] : undefined} editable={editable} onView={() => hero && viewPhoto(hero)} onAdd={() => { setPhotoPrompt(true); setTab('photos') }} />
        {target.kind === 'wine' && <WineDetails wine={target.record} data={data} editing={editing} setEditing={setEditing} editable={editable} busy={busy} setBusy={setBusy} setMessage={setMessage} householdId={householdId} onSaved={onSaved} onNavigate={onNavigate} onOpenBottle={onOpenBottle} onEnrichmentAccepted={returnToEnrichment ? onBack : undefined} />}
        {target.kind === 'winery' && <WineryDetails winery={target.record} data={data} editing={editing} setEditing={setEditing} editable={editable} busy={busy} setBusy={setBusy} setMessage={setMessage} householdId={householdId} onSaved={onSaved} onNavigate={onNavigate} onEnrichmentAccepted={returnToEnrichment ? onBack : undefined} />}
        {target.kind === 'opening' && <OpeningDetails opening={target.record} data={data} onNavigate={onNavigate} />}
        {target.kind === 'purchase' && <PurchaseDetails purchase={target.record} data={data} onNavigate={onNavigate} />}
        {target.kind === 'gift' && <GiftDetails gift={target.record} data={data} onNavigate={onNavigate} />}
        {target.kind === 'visit' && <VisitDetails visit={target.record} data={data} onNavigate={onNavigate} />}
      </>}
      {recordTarget && tabbedRecordTarget && tab === 'history' && <History target={target} data={data} onNavigate={onNavigate} />}
      {recordTarget && tabbedRecordTarget && tab === 'photos' && <PhotoPanel target={target} householdId={householdId} photos={relatedPhotos} urls={photoUrls} editable={editable} busy={busy} autoAdd={photoPrompt} onPrompted={() => setPhotoPrompt(false)} setBusy={setBusy} setMessage={setMessage} onSaved={onSaved} onView={viewPhoto} />}
      {target.kind === 'history' && <History target={target} data={data} onNavigate={onNavigate} />}
      {target.kind === 'favorites' && <Favorites data={data} onNavigate={onNavigate} />}
      {target.kind === 'statistics' && <Statistics data={data} />}
      {target.kind === 'storage' && <Storage data={data} householdId={householdId} editable={editable} onSaved={onSaved} />}
      {target.kind === 'documents' && <Documents householdId={householdId} data={data} editable={editable} onSaved={onSaved} onNavigate={onNavigate} />}
      {target.kind === 'enrichment' && <EnrichmentDashboard householdId={householdId} data={data} editable={editable} onSaved={onSaved} kind={enrichmentKind} setKind={setEnrichmentKind} filter={enrichmentFilter} setFilter={setEnrichmentFilter} onNavigate={(kind, id) => { enrichmentScroll.current = modalRef.current?.scrollTop ?? 0; if (kind === 'wine') { const wine = data.wines.find((item) => item.id === id); if (wine) onNavigate({ kind: 'wine', record: wine }) } else { const winery = data.wineries.find((item) => item.id === id); if (winery) onNavigate({ kind: 'winery', record: winery }) } }} />}
      {target.kind === 'trips' && <Empty title="Trips will appear when they are genuinely linked" text="The Travel Journal remains independent. This area will stay quiet until controlled two-way trip links are implemented." />}
      {target.kind === 'settings' && <Empty title="Private household collection" text="Authentication, member roles, private photos and documents, installable PWA behavior, and import guardrails are active." />}
      {message && <p className={/saved|uploaded|updated|deleted|accepted/i.test(message) ? 'form-message success' : 'form-message error'} role="status">{message}</p>}
    </section>
    {viewer && <PhotoViewer photo={viewer} url={photoUrls[viewer.id]} onClose={closeViewer} />}
  </div>
}

function RecordHero({ target, data, hasPhoto, url, editable, onView, onAdd }: { target: ManagementTarget; data: CellarData; hasPhoto: boolean; url?: string; editable: boolean; onView: () => void; onAdd: () => void }) {
  if (!['wine', 'winery', 'opening', 'purchase', 'gift', 'visit'].includes(target.kind)) return null
  let meta = '', summary = '', fallback = '🍷'
  if (target.kind === 'wine') { meta = `${target.record.wineryName ?? 'Independent wine'} · ${target.record.nonVintage ? 'NV' : target.record.vintage ?? 'Vintage not set'}`; summary = `${target.record.availableQuantity} available${target.record.averageRating ? ` · ${target.record.averageRating.toFixed(1)} / 5` : ''}` }
  if (target.kind === 'winery') { fallback = '♜'; meta = [target.record.city, target.record.state, target.record.country].filter(Boolean).join(', ') || 'Location not set'; summary = `${target.record.wineCount} wines · ${target.record.visitCount} visits` }
  if (target.kind === 'opening') { const wine = data.wines.find((item) => item.id === target.record.wineId); meta = target.record.status === 'open' ? 'Bottle opened' : 'Bottle enjoyed'; summary = `${date(target.record.openedAt)}${target.record.openedBy ? ` · ${target.record.openedBy}` : ''}`; fallback = wine?.category?.toLowerCase().includes('red') ? '🍷' : '🥂' }
  if (target.kind === 'purchase') { fallback = target.record.acquisitionType === 'gift' ? '🎁' : '🧾'; meta = target.record.acquisitionType === 'gift' ? `Gift${target.record.giftFrom ? ` from ${target.record.giftFrom}` : ''}` : target.record.purchaseLocation ?? 'Purchase'; summary = [target.record.acquisitionDate ? date(target.record.acquisitionDate) : null, target.record.totalCost == null ? null : money(target.record.totalCost)].filter(Boolean).join(' · ') }
  if (target.kind === 'gift') { fallback = '🎁'; meta = `Gifted to ${target.record.giftedTo}`; summary = date(target.record.giftedOn) }
  if (target.kind === 'visit') { fallback = '♜'; meta = 'Winery visit'; summary = date(target.record.visitDate) }
  return <section className="record-hero"><button className={`record-hero-media ${hasPhoto ? 'has-photo' : editable ? 'can-add-photo' : ''}`} onClick={hasPhoto ? onView : editable ? onAdd : undefined} disabled={!hasPhoto && !editable} aria-label={hasPhoto ? 'View photo' : editable ? 'Add photo' : undefined}>{url ? <img src={url} alt="" /> : hasPhoto ? <small>Loading photo…</small> : <span>{fallback}</span>}</button><p>{meta}</p><strong>{summary}</strong></section>
}

function WineDetails({ wine, data, editing, setEditing, editable, busy, setBusy, setMessage, householdId, onSaved, onNavigate, onOpenBottle, onEnrichmentAccepted }: { wine: WineRecord; data: CellarData; editing: boolean; setEditing: (value: boolean) => void; editable: boolean; busy: boolean; setBusy: (value: boolean) => void; setMessage: (value: string) => void; householdId: string; onSaved: () => Promise<void>; onNavigate: (target: ManagementTarget) => void; onOpenBottle: (wineId: string) => void; onEnrichmentAccepted?: () => void }) {
  const preferences = useMemo(() => Object.fromEntries(data.preferences.filter((preference) => preference.wineId === wine.id).map((preference) => [preference.personId, preference])), [data.preferences, wine.id])
  const purchases = data.purchaseItems.filter((item) => item.wineId === wine.id).map((item) => ({ item, purchase: data.purchases.find((purchase) => purchase.id === item.purchaseId) })).filter((entry) => entry.purchase)
  const save = async (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault(); if (!supabase || !editable) return
    setBusy(true); setMessage(''); const form = new FormData(event.currentTarget)
    try {
      const nonVintage = form.get('non_vintage') === 'on'
      const result = await supabase.from('wines').update({ winery_id: optional(form, 'winery_id'), name: String(form.get('name')).trim(), vintage: nonVintage ? null : numberOrNull(form, 'vintage'), non_vintage: nonVintage, blend_description: optional(form, 'blend_description'), style: optional(form, 'style'), category: optional(form, 'category'), sweetness: optional(form, 'sweetness'), country: optional(form, 'country'), state: optional(form, 'state'), vineyard: optional(form, 'vineyard'), closure: optional(form, 'closure'), official_winery_notes: optional(form, 'official_winery_notes'), personal_notes: optional(form, 'personal_notes'), favorite: form.get('favorite') === 'on' }).eq('household_id', householdId).eq('id', wine.id)
      if (result.error) throw result.error
      for (const person of data.people) { const preference = await supabase.from('wine_preferences').upsert({ household_id: householdId, wine_id: wine.id, person_id: person.id, favorite: form.get(`favorite_${person.id}`) === 'on', buy_again: optional(form, `buy_again_${person.id}`), notes: optional(form, `notes_${person.id}`) }, { onConflict: 'wine_id,person_id' }); if (preference.error) throw preference.error }
      await onSaved(); setEditing(false); setMessage('Saved successfully.')
    } catch (error) { setMessage(userError(error, 'The wine could not be saved. Please try again.')) } finally { setBusy(false) }
  }
  if (editing) return <form className="workflow-form detail-form" onSubmit={save}><label>Winery<select name="winery_id" defaultValue={wine.wineryId ?? ''}><option value="">No winery</option>{data.wineries.map((winery) => <option key={winery.id} value={winery.id}>{winery.name}</option>)}</select></label><label>Wine name<input name="name" required defaultValue={wine.name} /></label><div className="field-grid"><label>Vintage<input name="vintage" type="number" min="1800" defaultValue={wine.vintage ?? ''} /></label><label className="check-field paired-check-field"><input name="non_vintage" type="checkbox" defaultChecked={wine.nonVintage} /> Non-vintage</label></div><details className="more-details"><summary>More details</summary><div className="details-fields"><div className="field-grid"><label>Style<input name="style" defaultValue={wine.style ?? ''} /></label><label>Category<input name="category" defaultValue={wine.category ?? ''} /></label><label>Sweetness<input name="sweetness" defaultValue={wine.sweetness ?? ''} /></label><ClosureSelect defaultValue={wine.closure} /><label>Country<input name="country" defaultValue={wine.country ?? ''} /></label><StateSelect defaultValue={wine.state ?? ''} /></div><label>Vineyard<input name="vineyard" defaultValue={wine.vineyard ?? ''} /></label><label>Varietal or blend<input name="blend_description" defaultValue={wine.blendDescription ?? ''} /></label><label>Official winery notes<textarea name="official_winery_notes" rows={3} defaultValue={wine.officialWineryNotes ?? ''} /></label><label>Our notes<textarea name="personal_notes" rows={3} defaultValue={wine.personalNotes ?? ''} /></label><label className="check-field"><input name="favorite" type="checkbox" defaultChecked={wine.favorite} /> Household favorite</label>{data.people.map((person) => { const preference = preferences[person.id]; return <fieldset className="preference-card" key={person.id}><legend>{person.displayName}</legend><label className="check-field"><input name={`favorite_${person.id}`} type="checkbox" defaultChecked={preference?.favorite} /> Favorite</label><label>Buy again<select name={`buy_again_${person.id}`} defaultValue={preference?.buyAgain ?? ''}><option value="">Not set</option><option value="yes">Yes</option><option value="maybe">Maybe</option><option value="no">No</option></select></label><label>Notes<input name={`notes_${person.id}`} defaultValue={preference?.notes ?? ''} /></label></fieldset> })}</div></details><button className="primary-button" disabled={busy}>Save wine</button></form>
  return <div className="detail-content">{wine.availableQuantity > 0 && editable && <button className="primary-button full-button" onClick={() => onOpenBottle(wine.id)}>Open or gift a bottle</button>}<section className="detail-section"><h3>At a glance</h3><dl className="fact-grid"><Fact label="Vintage" value={wine.nonVintage ? 'NV' : wine.vintage?.toString()} /><Fact label="Type" value={wine.category ?? wine.style} /><Fact label="Location" value={wine.storageNames.join(', ') || 'Rack'} /><Fact label="Closure" value={wine.closure} /></dl></section><AgingSection wine={wine} data={data} editable={editable} householdId={householdId} onSaved={onSaved} setMessage={setMessage} />{wine.wineryId && <section className="detail-section"><h3>Winery</h3><RecordLink title={wine.wineryName ?? 'Winery'} subtitle={[wine.state, wine.country].filter(Boolean).join(', ')} onClick={() => { const winery = data.wineries.find((item) => item.id === wine.wineryId); if (winery) onNavigate({ kind: 'winery', record: winery }) }} /></section>}<RecordEnrichment kind="wine" entityId={wine.id} data={data} editable={editable} onSaved={onSaved} onAccepted={onEnrichmentAccepted} />{(wine.blendDescription || wine.vineyard || wine.officialWineryNotes) && <section className="detail-section"><h3>Cellar Details</h3>{wine.blendDescription && <p>{wine.blendDescription}</p>}{wine.vineyard && <p><strong>Vineyard:</strong> {wine.vineyard}</p>}{wine.officialWineryNotes && <details className="read-more"><summary>Previously recorded winery notes</summary><p>{wine.officialWineryNotes}</p></details>}</section>}{wine.personalNotes && <section className="detail-section"><p className="eyebrow burgundy">PERSONAL</p><h3>Our Notes</h3><p>{wine.personalNotes}</p></section>}{purchases.length > 0 && <section className="detail-section"><h3>How it came to us</h3><div className="record-list">{purchases.map(({ item, purchase }) => <RecordLink key={item.id} title={`${item.quantity} bottle${item.quantity === 1 ? '' : 's'} · ${purchase!.acquisitionType === 'gift' ? 'Gift' : 'Purchased'}`} subtitle={[purchase!.acquisitionDate ? date(purchase!.acquisitionDate) : null, purchase!.acquisitionType === 'gift' ? purchase!.giftFrom : purchase!.purchaseLocation, item.totalCost == null ? null : money(item.totalCost)].filter(Boolean).join(' · ')} onClick={() => onNavigate({ kind: 'purchase', record: purchase! })} />)}</div></section>}</div>
}

function AgingSection({ wine, data, editable, householdId, onSaved, setMessage }: { wine: WineRecord; data: CellarData; editable: boolean; householdId: string; onSaved: () => Promise<void>; setMessage: (value: string) => void }) {
  const guidance = data.drinkingGuidance.find((item) => item.wineId === wine.id)
  const agingBottles = data.bottles.filter((bottle) => bottle.wineId === wine.id && bottle.status === 'active' && bottle.isAging)
  const [aging, setAging] = useState(agingBottles.length > 0)
  const [quantity, setQuantity] = useState(Math.max(1, agingBottles.length))
  const [overrideYear, setOverrideYear] = useState<number | ''>(agingBottles.find((bottle) => bottle.userHoldUntilYear)?.userHoldUntilYear ?? '')
  const [saving, setSaving] = useState(false)
  if (!guidance) return <section className="detail-section aging-section"><h3>When to Enjoy</h3><p className="empty-copy compact">There is not enough reliable information to estimate a drinking window for this wine yet.</p></section>
  const status = guidanceStatus(guidance)
  const window = guidance.drinkWindowStartYear || guidance.drinkWindowEndYear ? `${guidance.drinkWindowStartYear ?? 'Now'}–${guidance.drinkWindowEndYear ?? 'Open'}` : 'Not established'
  const saveAging = async (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault(); if (!supabase || !editable) return
    setSaving(true); setMessage('')
    try {
      const result = await supabase.rpc('set_wine_aging_quantity', { p_household_id: householdId, p_wine_id: wine.id, p_aging_count: aging ? quantity : 0, p_user_hold_override_year: aging && overrideYear !== '' ? overrideYear : null })
      if (result.error) throw result.error
      await onSaved(); setMessage(aging ? `${quantity} bottle${quantity === 1 ? '' : 's'} set aside for aging.` : 'Aging bottles updated.')
    } catch (error) { setMessage(userError(error, 'The aging selection could not be saved. Please try again.')) } finally { setSaving(false) }
  }
  return <section className="detail-section aging-section"><div className="aging-heading"><div><h3>When to Enjoy</h3><p>{wine.availableQuantity} on hand · {agingBottles.length} Aging</p></div>{status && <span className={`guidance-status ${status.toLowerCase().replace(' ', '-')}`}>{status}</span>}</div><dl className="fact-grid"><Fact label="Drinking window" value={window} /><Fact label="Suggested hold" value={guidance.suggestedHoldUntilYear ? `Until ${guidance.suggestedHoldUntilYear}` : 'No hold suggested'} /></dl>{guidance.rationale && <p className="guidance-rationale">{guidance.rationale}</p>}<p className="guidance-source">{guidanceSourceLabel(guidance.source)} · {guidance.confidence} confidence{guidance.sourceUrl && <>{' · '}<a href={guidance.sourceUrl} target="_blank" rel="noreferrer">Source ↗</a></>}</p>{editable && wine.availableQuantity > 0 && <form className="aging-control" onSubmit={saveAging}><label className="check-field"><input type="checkbox" checked={aging} onChange={(event) => setAging(event.target.checked)} /> Aging</label>{aging && <><label>How many bottles should be set aside?<input type="number" min="1" max={wine.availableQuantity} step="1" value={quantity} onChange={(event) => setQuantity(Math.max(1, Math.min(wine.availableQuantity, Number(event.target.value))))} /></label><details><summary>Change hold year</summary><label>Hold until<input type="number" min={new Date().getFullYear()} max="2200" placeholder={String(guidance.suggestedHoldUntilYear ?? '')} value={overrideYear} onChange={(event) => setOverrideYear(event.target.value ? Number(event.target.value) : '')} /></label><small>Your hold year overrides the suggestion for the selected bottles.</small></details></>}<button className="secondary-button" disabled={saving}>{saving ? 'Saving…' : 'Save Aging selection'}</button></form>}</section>
}

function WineryDetails({ winery, data, editing, setEditing, editable, busy, setBusy, setMessage, householdId, onSaved, onNavigate, onEnrichmentAccepted }: { winery: WineryRecord; data: CellarData; editing: boolean; setEditing: (value: boolean) => void; editable: boolean; busy: boolean; setBusy: (value: boolean) => void; setMessage: (value: string) => void; householdId: string; onSaved: () => Promise<void>; onNavigate: (target: ManagementTarget) => void; onEnrichmentAccepted?: () => void }) {
  const save = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); if (!supabase || !editable) return; setBusy(true); setMessage(''); const form = new FormData(event.currentTarget); try { const result = await supabase.from('wineries').update({ name: String(form.get('name')).trim(), country: optional(form, 'country'), state: optional(form, 'state'), region: optional(form, 'region'), city: optional(form, 'city'), address: optional(form, 'address'), website_url: optional(form, 'website_url'), contact_phone: optional(form, 'contact_phone'), contact_email: optional(form, 'contact_email'), notes: optional(form, 'notes'), favorite: form.get('favorite') === 'on', would_visit_again: optional(form, 'would_visit_again') }).eq('household_id', householdId).eq('id', winery.id); if (result.error) throw result.error; await onSaved(); setEditing(false); setMessage('Saved successfully.') } catch (error) { setMessage(userError(error, 'The winery could not be saved. Please try again.')) } finally { setBusy(false) } }
  if (editing) return <form className="workflow-form detail-form" onSubmit={save}><label>Name<input name="name" required defaultValue={winery.name} /></label><div className="field-grid"><label>City<input name="city" defaultValue={winery.city ?? ''} /></label><StateSelect defaultValue={winery.state ?? ''} /></div><details className="more-details"><summary>More details</summary><div className="details-fields"><div className="field-grid"><label>Region<input name="region" defaultValue={winery.region ?? ''} /></label><label>Country<input name="country" defaultValue={winery.country ?? ''} /></label></div><label>Address<input name="address" defaultValue={winery.address ?? ''} /></label><label>Website<input name="website_url" type="url" defaultValue={winery.websiteUrl ?? ''} /></label><div className="field-grid"><label>Phone<input name="contact_phone" type="tel" defaultValue={winery.contactPhone ?? ''} /></label><label>Email<input name="contact_email" type="email" defaultValue={winery.contactEmail ?? ''} /></label></div><label>Would visit again<select name="would_visit_again" defaultValue={winery.wouldVisitAgain ?? ''}><option value="">Not set</option><option value="yes">Yes</option><option value="maybe">Maybe</option><option value="no">No</option></select></label><label className="check-field"><input name="favorite" type="checkbox" defaultChecked={winery.favorite} /> Favorite winery</label><label>Notes<textarea name="notes" rows={4} defaultValue={winery.notes ?? ''} /></label></div></details><button className="primary-button" disabled={busy}>Save winery</button></form>
  const wines = data.wines.filter((wine) => wine.wineryId === winery.id), visits = data.visits.filter((visit) => visit.wineryId === winery.id)
  return <div className="detail-content"><RecordEnrichment kind="winery" entityId={winery.id} data={data} editable={editable} onSaved={onSaved} onAccepted={onEnrichmentAccepted} />{(winery.notes || winery.websiteUrl) && <section className="detail-section"><p className="eyebrow burgundy">PERSONAL / RECORDED</p><h3>Our Winery Notes</h3>{winery.notes && <p>{winery.notes}</p>}{winery.websiteUrl && <a className="inline-link" href={winery.websiteUrl} target="_blank" rel="noreferrer">Recorded website ↗</a>}</section>}<section className="detail-section"><h3>Wines from here</h3>{wines.length ? <div className="record-list">{wines.map((wine) => <RecordLink key={wine.id} title={wine.name} subtitle={`${wine.nonVintage ? 'NV' : wine.vintage ?? 'Vintage not set'} · ${wine.availableQuantity} available`} onClick={() => onNavigate({ kind: 'wine', record: wine })} />)}</div> : <p className="empty-copy compact">No wines linked yet.</p>}</section>{visits.length > 0 && <section className="detail-section"><h3>Visits</h3><div className="record-list">{visits.map((visit) => <RecordLink key={visit.id} title={date(visit.visitDate)} subtitle={visit.notes ?? 'Winery visit'} onClick={() => onNavigate({ kind: 'visit', record: visit })} />)}</div></section>}</div>
}

function OpeningDetails({ opening, data, onNavigate }: { opening: OpeningRecord; data: CellarData; onNavigate: (target: ManagementTarget) => void }) {
  const wine = data.wines.find((item) => item.id === opening.wineId), reviews = data.reviews.filter((review) => review.openingId === opening.id)
  return <div className="detail-content">{wine && <section className="detail-section"><h3>Wine</h3><RecordLink title={wine.name} subtitle={`${wine.wineryName ?? 'Winery not set'} · ${wine.nonVintage ? 'NV' : wine.vintage ?? 'Vintage not set'}`} onClick={() => onNavigate({ kind: 'wine', record: wine })} /></section>}<section className="detail-section"><h3>The memory</h3><dl className="fact-grid"><Fact label="Opened" value={date(opening.openedAt)} /><Fact label="Opened by" value={opening.openedBy ?? 'Not specified'} /><Fact label="Status" value={opening.status === 'open' ? 'Still open' : 'Finished'} /><Fact label="Occasion" value={opening.occasion} /></dl>{opening.enjoyedWith && <p><strong>Enjoyed with:</strong> {opening.enjoyedWith}</p>}{opening.memoryNotes && <p>{opening.memoryNotes}</p>}{opening.issueType && <p className="issue-note"><strong>Issue:</strong> {opening.issueType.replace('_', ' ')}{opening.issueNotes ? ` · ${opening.issueNotes}` : ''}</p>}</section>{reviews.length > 0 && <section className="detail-section"><h3>What we thought</h3><div className="review-grid">{reviews.map((review) => { const person = data.people.find((item) => item.id === review.personId); return <article key={review.id}><strong>{person?.displayName ?? 'Household member'}</strong><p>{review.rating ? `${review.rating} / 5` : 'Not rated'}{review.buyAgain ? ` · Buy again: ${review.buyAgain}` : ''}</p>{review.tastingNotes && <p>{review.tastingNotes}</p>}</article> })}</div></section>}</div>
}

function PurchaseDetails({ purchase, data, onNavigate }: { purchase: PurchaseRecord; data: CellarData; onNavigate: (target: ManagementTarget) => void }) {
  const items = data.purchaseItems.filter((item) => item.purchaseId === purchase.id), visit = purchase.wineryVisitId ? data.visits.find((item) => item.id === purchase.wineryVisitId) : null
  const receivedAsGift = purchase.acquisitionType === 'gift'
  return <div className="detail-content"><section className="detail-section"><h3>{receivedAsGift ? 'Gift received' : 'Purchase'}</h3><dl className="fact-grid"><Fact label={receivedAsGift ? 'Date received' : 'Date'} value={purchase.acquisitionDate ? date(purchase.acquisitionDate) : undefined} />{receivedAsGift ? <Fact label="Gift from" value={purchase.giftFrom} /> : <><Fact label="Total" value={purchase.totalCost == null ? undefined : money(purchase.totalCost)} /><Fact label="Purchased by" value={purchase.purchasedBy} /><Fact label="Selected by" value={purchase.selectedBy} /></>}</dl>{purchase.notes && <p>{purchase.notes}</p>}</section><section className="detail-section"><h3>{receivedAsGift ? 'Wines received' : 'Wines purchased'}</h3><div className="record-list">{items.map((item) => { const wine = data.wines.find((entry) => entry.id === item.wineId); return wine ? <RecordLink key={item.id} title={wine.name} subtitle={`${item.quantity} bottle${item.quantity === 1 ? '' : 's'}${item.totalCost == null ? '' : ` · ${money(item.totalCost)}`}`} onClick={() => onNavigate({ kind: 'wine', record: wine })} /> : null })}</div></section>{visit && <section className="detail-section"><h3>Related visit</h3><RecordLink title={date(visit.visitDate)} subtitle="Winery visit" onClick={() => onNavigate({ kind: 'visit', record: visit })} /></section>}</div>
}

function GiftDetails({ gift, data, onNavigate }: { gift: GiftRecord; data: CellarData; onNavigate: (target: ManagementTarget) => void }) {
  const wine = data.wines.find((item) => item.id === gift.wineId)
  return <div className="detail-content">{wine && <section className="detail-section"><h3>Wine</h3><RecordLink title={wine.name} subtitle={`${wine.wineryName ?? 'Winery not set'} · ${wine.nonVintage ? 'NV' : wine.vintage ?? 'Vintage not set'}`} onClick={() => onNavigate({ kind: 'wine', record: wine })} /></section>}<section className="detail-section"><h3>Gift</h3><dl className="fact-grid"><Fact label="Gifted to" value={gift.giftedTo} /><Fact label="Date" value={date(gift.giftedOn)} /></dl>{gift.occasionNote && <p>{gift.occasionNote}</p>}</section></div>
}

function VisitDetails({ visit, data, onNavigate }: { visit: VisitRecord; data: CellarData; onNavigate: (target: ManagementTarget) => void }) {
  const winery = data.wineries.find((item) => item.id === visit.wineryId), purchases = data.purchases.filter((purchase) => purchase.wineryVisitId === visit.id)
  return <div className="detail-content">{winery && <section className="detail-section"><h3>Winery</h3><RecordLink title={winery.name} subtitle={[winery.city, winery.state].filter(Boolean).join(', ')} onClick={() => onNavigate({ kind: 'winery', record: winery })} /></section>}<section className="detail-section"><h3>Visit memory</h3><dl className="fact-grid"><Fact label="Date" value={date(visit.visitDate)} /><Fact label="Visit again" value={visit.wouldVisitAgain ?? 'Not specified'} /></dl>{visit.notes && <p>{visit.notes}</p>}</section>{purchases.length > 0 && <section className="detail-section"><h3>Purchases from this visit</h3><div className="record-list">{purchases.map((purchase) => <RecordLink key={purchase.id} title={purchase.purchaseLocation ?? 'Purchase'} subtitle={[purchase.acquisitionDate ? date(purchase.acquisitionDate) : null, purchase.totalCost == null ? null : money(purchase.totalCost)].filter(Boolean).join(' · ')} onClick={() => onNavigate({ kind: 'purchase', record: purchase })} />)}</div></section>}</div>
}

function Fact({ label, value }: { label: string; value?: string | null }) { return <div><dt>{label}</dt><dd>{value || 'Not set'}</dd></div> }
function RecordLink({ title, subtitle, onClick }: { title: string; subtitle?: string; onClick: () => void }) { return <button className="record-link" onClick={onClick}><span><strong>{title}</strong>{subtitle && <small>{subtitle}</small>}</span><span aria-hidden="true">›</span></button> }

function History({ target, data, onNavigate }: { target: ManagementTarget; data: CellarData; onNavigate: (target: ManagementTarget) => void }) {
  const wine = target.kind === 'wine' ? target.record : target.kind === 'opening' || target.kind === 'gift' ? data.wines.find((item) => item.id === target.record.wineId) : null
  const winery = target.kind === 'winery' ? target.record : target.kind === 'visit' ? data.wineries.find((item) => item.id === target.record.wineryId) : null
  const purchaseOnly = target.kind === 'purchase' ? target.record.id : null, openingOnly = target.kind === 'opening' ? target.record.id : null, giftOnly = target.kind === 'gift' ? target.record.id : null, visitOnly = target.kind === 'visit' ? target.record.id : null
  const events: Array<{ key: string; at: string | null; title: string; body: string; target: ManagementTarget }> = []
  if (!['opening', 'gift', 'visit', 'winery'].includes(target.kind)) for (const item of data.purchaseItems.filter((entry) => (!wine || entry.wineId === wine.id) && (!purchaseOnly || entry.purchaseId === purchaseOnly))) { const purchase = data.purchases.find((entry) => entry.id === item.purchaseId), itemWine = data.wines.find((entry) => entry.id === item.wineId); if (purchase) { const receivedAsGift = purchase.acquisitionType === 'gift'; events.push({ key: `purchase-${item.id}`, at: purchase.acquisitionDate, title: `${receivedAsGift ? 'Received as a gift' : 'Purchased'} · ${item.quantity} bottle${item.quantity === 1 ? '' : 's'}${itemWine && !wine ? ` · ${itemWine.name}` : ''}`, body: receivedAsGift ? [purchase.giftFrom ? `From ${purchase.giftFrom}` : null, purchase.notes].filter(Boolean).join(' · ') : [purchase.purchaseLocation, item.totalCost == null ? null : money(item.totalCost), purchase.purchasedBy].filter(Boolean).join(' · '), target: { kind: 'purchase', record: purchase } }) } }
  if (!['purchase', 'gift', 'visit', 'winery'].includes(target.kind)) for (const opening of data.openings.filter((entry) => (!wine || entry.wineId === wine.id) && (!openingOnly || entry.id === openingOnly))) { const itemWine = data.wines.find((entry) => entry.id === opening.wineId); events.push({ key: `opening-${opening.id}`, at: opening.openedAt, title: `${opening.status === 'open' ? 'Bottle opened' : 'Bottle enjoyed'}${itemWine && !wine ? ` · ${itemWine.name}` : ''}`, body: [opening.openedBy, opening.occasion, opening.memoryNotes].filter(Boolean).join(' · '), target: { kind: 'opening', record: opening } }) }
  if (!['purchase', 'opening', 'visit', 'winery'].includes(target.kind)) for (const gift of data.giftsGiven.filter((entry) => (!wine || entry.wineId === wine.id) && (!giftOnly || entry.id === giftOnly))) { const itemWine = data.wines.find((entry) => entry.id === gift.wineId); events.push({ key: `gift-${gift.id}`, at: gift.giftedOn, title: `1 bottle gifted to ${gift.giftedTo}${itemWine && !wine ? ` · ${itemWine.name}` : ''}`, body: gift.occasionNote ?? '', target: { kind: 'gift', record: gift } }) }
  if (!['purchase', 'opening', 'gift', 'wine'].includes(target.kind)) for (const visit of data.visits.filter((entry) => (!winery || entry.wineryId === winery.id) && (!visitOnly || entry.id === visitOnly))) { const itemWinery = data.wineries.find((entry) => entry.id === visit.wineryId); events.push({ key: `visit-${visit.id}`, at: visit.visitDate, title: `Winery visit${itemWinery && !winery ? ` · ${itemWinery.name}` : ''}`, body: visit.notes ?? '', target: { kind: 'visit', record: visit } }) }
  events.sort((a, b) => (b.at ?? '').localeCompare(a.at ?? ''))
  return <div className="history-list">{events.length ? events.map((event) => <button className="history-card" key={event.key} onClick={() => onNavigate(event.target)}><small>{event.at ? date(event.at) : 'Date unknown'}</small><strong>{event.title}</strong>{event.body && <p>{event.body}</p>}<span aria-hidden="true">›</span></button>) : <p className="empty-copy">No history yet.</p>}</div>
}

function Favorites({ data, onNavigate }: { data: CellarData; onNavigate: (target: ManagementTarget) => void }) { const wines = data.wines.filter((wine) => wine.favorite || data.preferences.some((preference) => preference.wineId === wine.id && preference.favorite)); return <div className="record-list standalone-list">{wines.length ? wines.map((wine) => <RecordLink key={wine.id} title={wine.name} subtitle={`${wine.wineryName ?? 'Winery not set'} · ${wine.nonVintage ? 'NV' : wine.vintage ?? 'Vintage not set'}`} onClick={() => onNavigate({ kind: 'wine', record: wine })} />) : <p className="empty-copy">Favorites will appear here as each household member marks them.</p>}</div> }

function PhotoPanel({ target, householdId, photos, urls, editable, busy, autoAdd, onPrompted, setBusy, setMessage, onSaved, onView }: { target: ManagementTarget; householdId: string; photos: PhotoRecord[]; urls: Record<string, string>; editable: boolean; busy: boolean; autoAdd: boolean; onPrompted: () => void; setBusy: (value: boolean) => void; setMessage: (value: string) => void; onSaved: () => Promise<void>; onView: (photo: PhotoRecord) => void }) {
  const inputRef = useRef<HTMLInputElement | null>(null)
  useEffect(() => { if (autoAdd && editable) requestAnimationFrame(() => { inputRef.current?.click(); onPrompted() }) }, [autoAdd, editable, onPrompted])
  const upload = async (file: File) => { if (!supabase || !('record' in target)) return; setBusy(true); setMessage(''); const parent = target.kind === 'wine' ? ['wines', 'wine_id'] : target.kind === 'winery' ? ['wineries', 'winery_id'] : target.kind === 'opening' ? ['openings', 'opening_id'] : target.kind === 'purchase' ? ['purchases', 'purchase_id'] : ['visits', 'winery_visit_id']; const path = `${householdId}/${parent[0]}/${target.record.id}/${createUniqueId()}-${safeName(file.name)}`; try { validatePhoto(file); const stored = await supabase.storage.from('cellar-photos').upload(path, file, { contentType: file.type, upsert: false }); if (stored.error) throw stored.error; const result = await supabase.from('photos').insert({ household_id: householdId, [parent[1]]: target.record.id, storage_path: path, original_filename: file.name, mime_type: file.type, file_size_bytes: file.size, is_hero: (target.kind === 'wine' || target.kind === 'winery') && photos.length === 0 }); if (result.error) { await supabase.storage.from('cellar-photos').remove([path]); throw result.error } await onSaved(); setMessage('Private photo uploaded.') } catch (error) { setMessage(userError(error, 'The photo could not be uploaded. Please try again.')) } finally { setBusy(false) } }
  const setHero = async (photo: PhotoRecord) => { if (!supabase || (target.kind !== 'wine' && target.kind !== 'winery')) return; setBusy(true); setMessage(''); const column = target.kind === 'wine' ? 'wine_id' : 'winery_id'; const reset = await supabase.from('photos').update({ is_hero: false }).eq('household_id', householdId).eq(column, target.record.id); const result = reset.error ? reset : await supabase.from('photos').update({ is_hero: true }).eq('household_id', householdId).eq('id', photo.id); if (result.error) setMessage(userError(result.error, 'The hero photo could not be changed.')); else { await onSaved(); setMessage('Hero photo updated.') } setBusy(false) }
  const remove = async (photo: PhotoRecord) => { if (!supabase || !window.confirm('Remove this photo permanently?')) return; setBusy(true); setMessage(''); const stored = await supabase.storage.from('cellar-photos').remove([photo.storagePath]); const result = stored.error ? stored : await supabase.from('photos').delete().eq('household_id', householdId).eq('id', photo.id); if (result.error) setMessage(userError(result.error, 'The photo could not be removed.')); else { await onSaved(); setMessage('Photo deleted.') } setBusy(false) }
  return <section className="photo-panel"><div className="photo-panel-lead"><p>Private to signed-in household members.</p>{editable && <label className="camera-button" aria-label="Add photo">＋<input ref={inputRef} type="file" accept="image/jpeg,image/png,image/webp,image/heic,image/heif" capture="environment" disabled={busy} onChange={(event) => { const file = event.target.files?.[0]; if (file) void upload(file); event.currentTarget.value = '' }} /></label>}</div>{photos.length ? <div className="gallery">{photos.map((photo) => <figure key={photo.id}><button className="gallery-image" onClick={() => onView(photo)}>{urls[photo.id] ? <img src={urls[photo.id]} alt={photo.caption ?? 'Cellar photo'} /> : <span>Loading…</span>}</button><figcaption>{photo.caption ?? (photo.isHero ? 'Hero photo' : 'Photo')}</figcaption>{editable && <div className="photo-actions">{(target.kind === 'wine' || target.kind === 'winery') && <button onClick={() => void setHero(photo)} disabled={busy || photo.isHero}>{photo.isHero ? 'Hero' : 'Make hero'}</button>}<button onClick={() => void remove(photo)} disabled={busy}>Delete</button></div>}</figure>)}</div> : <button className="photo-empty" type="button" onClick={() => inputRef.current?.click()} disabled={!editable || busy}><span>◇</span><p>{editable ? 'Add the first photo' : 'No photos yet.'}</p></button>}</section>
}

function PhotoViewer({ photo, url, onClose }: { photo: PhotoRecord; url?: string; onClose: () => void }) { return <div className="photo-viewer" role="dialog" aria-modal="true" aria-label="Photo viewer" onMouseDown={(event) => event.target === event.currentTarget && onClose()}><button className="photo-viewer-close" onClick={onClose} aria-label="Close photo">×</button><figure>{url ? <img src={url} alt={photo.caption ?? 'Cellar photo'} /> : <p className="photo-viewer-loading">Loading photo…</p>}{photo.caption && <figcaption>{photo.caption}</figcaption>}</figure></div> }

function Statistics({ data }: { data: CellarData }) { const byStyle = Object.entries(data.wines.reduce<Record<string, number>>((result, wine) => { const key = wine.category ?? wine.style ?? 'Uncategorized'; result[key] = (result[key] ?? 0) + wine.availableQuantity; return result }, {})).sort((a, b) => b[1] - a[1]); return <><div className="snapshot-grid modal-snapshot"><article className="snapshot-card"><strong>{data.snapshot.purchasedBottles}</strong><span>Purchased</span></article><article className="snapshot-card"><strong>{data.snapshot.giftsReceived}</strong><span>Gifts received</span></article><article className="snapshot-card"><strong>{data.snapshot.bottlesEnjoyed}</strong><span>Opened / consumed</span></article><article className="snapshot-card"><strong>{data.snapshot.giftedAway}</strong><span>Gifted away</span></article><article className="snapshot-card"><strong>{data.snapshot.currentBottles}</strong><span>Currently on hand</span></article><article className="snapshot-card"><strong>{money(data.snapshot.recordedValue)}</strong><span>Recorded value</span></article></div><section className="detail-section"><h3>Collection by style</h3>{byStyle.map(([label, value]) => <div className="stat-row" key={label}><span>{label}</span><i style={{ width: `${value / Math.max(1, ...byStyle.map((row) => row[1])) * 100}%` }} /><strong>{value}</strong></div>)}</section></> }

function Storage({ data, householdId, editable, onSaved }: { data: CellarData; householdId: string; editable: boolean; onSaved: () => Promise<void> }) {
  const [busy, setBusy] = useState(false), [message, setMessage] = useState('')
  const [mode, setMode] = useState<'move' | 'adjust_out' | 'adjust_in' | 'location'>('move')
  const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const formElement = event.currentTarget; if (!supabase || !editable) return; setBusy(true); setMessage(''); const form = new FormData(formElement); try { const mode = String(form.get('mode')); if (mode === 'location') { const result = await supabase.from('storage_locations').insert({ household_id: householdId, name: String(form.get('name')).trim(), location_type: optional(form, 'location_type') || 'area', description: optional(form, 'description') }); if (result.error) throw result.error } else { const [itemId, locationId] = String(form.get('bottle_lot')).split('|'), quantity = Number(form.get('quantity')); const result = mode === 'move' ? await supabase.rpc('move_inventory', { p_household_id: householdId, p_purchase_item_id: itemId, p_from_location_id: locationId, p_to_location_id: String(form.get('to_location_id')), p_quantity: quantity, p_reason: optional(form, 'reason') }) : await supabase.rpc('adjust_inventory', { p_household_id: householdId, p_purchase_item_id: itemId, p_storage_location_id: locationId, p_quantity_delta: mode === 'adjust_in' ? quantity : -quantity, p_reason: String(form.get('reason')).trim() }); if (result.error) throw result.error } await onSaved(); formElement.reset(); formElement.closest('details')?.removeAttribute('open'); setMessage('Saved successfully.') } catch (error) { setMessage(userError(error, 'The storage change could not be saved. Please try again.')) } finally { setBusy(false) } }
  return <><div className="record-list standalone-list">{data.locations.map((location) => <article className="static-record" key={location.id}><strong>{location.name}</strong><small>{location.locationType} · {data.bottleLots.filter((lot) => lot.storageLocationId === location.id).reduce((sum, lot) => sum + lot.quantity, 0)} bottles</small></article>)}</div>{editable && <details className="more-details standalone-details"><summary>Manage storage</summary><form className="workflow-form" onSubmit={submit}><label>Action<select name="mode" value={mode} onChange={(event) => setMode(event.target.value as typeof mode)}><option value="move">Move bottles</option><option value="adjust_out">Reduce count</option><option value="adjust_in">Increase count</option><option value="location">Add storage area</option></select></label>{mode === 'location' ? <><label>New area name<input name="name" required /></label><label>Area type<input name="location_type" defaultValue="area" /></label><label>Description<input name="description" /></label></> : <><label>Bottle lot<select name="bottle_lot" required defaultValue=""><option value="" disabled>Choose a lot</option>{data.bottleLots.map((lot) => <option key={`${lot.purchaseItemId}-${lot.storageLocationId}`} value={`${lot.purchaseItemId}|${lot.storageLocationId}`}>{lot.wineLabel} · {lot.storageLocationName} ({lot.quantity})</option>)}</select></label>{mode === 'move' && <label>Destination<select name="to_location_id" required defaultValue=""><option value="" disabled>Choose destination</option>{data.locations.filter((location) => location.isActive).map((location) => <option key={location.id} value={location.id}>{location.name}</option>)}</select></label>}<label>Quantity<input name="quantity" type="number" min="0.01" step="0.01" defaultValue="1" required /></label><label>Reason<input name="reason" required={mode !== 'move'} /></label></>}<button className="primary-button" disabled={busy}>{busy ? 'Saving…' : 'Save storage change'}</button></form></details>}{message && <p className="form-message success">{message}</p>}</>
}

function Documents({ householdId, data, editable, onSaved, onNavigate }: { householdId: string; data: CellarData; editable: boolean; onSaved: () => Promise<void>; onNavigate: (target: ManagementTarget) => void }) {
  const [busy, setBusy] = useState(false), [message, setMessage] = useState('')
  const upload = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const formElement = event.currentTarget; if (!supabase) return; setBusy(true); const form = new FormData(formElement), file = form.get('file'); try { if (!(file instanceof File) || !file.size) throw new Error('Choose a receipt or document.'); const purchaseId = String(form.get('purchase_id')), path = `${householdId}/purchases/${purchaseId}/${createUniqueId()}-${safeName(file.name)}`; const stored = await supabase.storage.from('cellar-documents').upload(path, file, { contentType: file.type, upsert: false }); if (stored.error) throw stored.error; const result = await supabase.from('documents').insert({ household_id: householdId, purchase_id: purchaseId, document_type: optional(form, 'document_type') || 'receipt', display_title: String(form.get('display_title')).trim(), document_date: optional(form, 'document_date'), storage_path: path, original_filename: file.name, mime_type: file.type, file_size_bytes: file.size }); if (result.error) { await supabase.storage.from('cellar-documents').remove([path]); throw result.error } await onSaved(); formElement.reset(); formElement.closest('details')?.removeAttribute('open'); setMessage('Document uploaded.') } catch (error) { setMessage(userError(error, 'The document could not be uploaded. Please try again.')) } finally { setBusy(false) } }
  const open = async (path: string) => { if (!supabase) return; const result = await supabase.storage.from('cellar-documents').createSignedUrl(path, 120); if (result.error) setMessage(result.error.message); else window.open(result.data.signedUrl, '_blank', 'noopener,noreferrer') }
  return <><div className="record-list standalone-list">{data.documents.length ? data.documents.map((document) => { const purchase = data.purchases.find((item) => item.id === document.purchaseId); return <div className="document-row" key={document.id}><button onClick={() => void open(document.storagePath)}><strong>{document.displayTitle}</strong><small>{document.originalFilename}{document.documentDate ? ` · ${date(document.documentDate)}` : ''}</small></button>{purchase && <button className="document-purchase" onClick={() => onNavigate({ kind: 'purchase', record: purchase })}>Purchase ›</button>}</div> }) : <p className="empty-copy">No receipts or documents yet.</p>}</div>{editable && <details className="more-details standalone-details"><summary>Upload document</summary><form className="workflow-form" onSubmit={upload}><label>Purchase<select name="purchase_id" required defaultValue=""><option value="" disabled>Select purchase</option>{data.purchases.map((purchase) => <option key={purchase.id} value={purchase.id}>{purchase.acquisitionDate ?? 'Date unknown'} · {purchase.purchaseLocation ?? 'Purchase'}</option>)}</select></label><label>Title<input name="display_title" required placeholder="Receipt" /></label><label>Type<select name="document_type"><option value="receipt">Receipt</option><option value="invoice">Invoice</option><option value="other">Other</option></select></label><label>File<input name="file" type="file" accept="image/jpeg,image/png,image/webp,image/heic,image/heif,application/pdf" capture="environment" required /></label><button className="primary-button" disabled={busy}>{busy ? 'Uploading…' : 'Upload private document'}</button></form></details>}{message && <p className="form-message">{message}</p>}</>
}

function Empty({ title, text }: { title: string; text: string }) { return <article className="empty-feature modal-empty"><div><h3>{title}</h3><p>{text}</p></div></article> }
